import { SkillDefinition } from './types.js';

export const aiSkills: SkillDefinition[] = [
  {
    name: 'ai-llm',
    version: '1.0.0',
    description: 'Manages LLM discovery, prompt layer composition, context budgeting, and model routing.',
    category: 'ai',
    dir: 'llm',
    risk: 'safe',
    requires_permission: false,
    required_tools: [],
    optional_tools: ['diagnostics_run'],
    fallbacks: 'Default to lightweight free-tier models (Gemini Flash, Groq LPU).',
    title: 'LLM Orchestration & Model Routing',
    purpose: 'Select and route tasks to optimal LLMs based on capability requirements, latency, context, and cost.',
    when_to_activate: 'Activate on model selection, /model command, or when routing tasks autonomously.',
    inputs: 'Task complexity, required context tokens, privacy constraints, available providers.',
    preconditions: 'ProviderRouter must be configured with registered providers.',
    procedure: `1. Analyze task requirements (code generation, architectural reasoning, fast triage).
2. Calculate required context window size.
3. Check provider availability (local MLX/Ollama vs cloud Gemini/Groq/NIM).
4. Evaluate cost and latency tradeoffs.
5. Select target model and configure temperature/sampling parameters.
6. Dispatch generation request through ResponseNormalizer.`,
    tool_usage: 'Operates via ProviderRouter in @berkelium/providers.',
    safety: 'Respect user privacy settings; never send sensitive code to cloud if privacy mode is LOCAL.',
    permissions: 'Safe model routing.',
    verification: 'Confirm selected model supports the required context length and tool calling schema.',
    failure_handling: 'If selected provider is unavailable, fallback gracefully through ProviderRouter fallback chain.',
    output_contract: 'ModelRoutingDecision with modelId, provider, contextLimit, isLocal: boolean.',
    examples: 'Routing a 150,000 token context task to Gemini 2.5 Flash with 1M context.',
    related_skills: ['core-context-management', 'ai-inference'],
  },
  {
    name: 'ai-inference',
    version: '1.0.0',
    description: 'Executes local and cloud LLM inference loops, token streaming, and response normalization.',
    category: 'ai',
    dir: 'inference',
    risk: 'safe',
    requires_permission: false,
    required_tools: [],
    optional_tools: [],
    fallbacks: 'Degrade from streaming tokens to block response completion.',
    title: 'Model Inference & Streaming Normalization',
    purpose: 'Execute inference streams across diverse providers and normalize chunks into unified AgentEvents.',
    when_to_activate: 'Activate during autonomous reasoning and generation turns.',
    inputs: 'Prompt messages array, model target, temperature, stop sequences.',
    preconditions: 'Target provider adapter must be authenticated.',
    procedure: `1. Format prompt messages adhering to provider API specification.
2. Open streaming connection to provider inference endpoint.
3. Stream tokens through ResponseNormalizer.
4. Detect tool calls and extract structured JSON arguments.
5. Emit typed AgentEvents (token_received, tool_requested) over EventBus.
6. Return complete normalized response.`,
    tool_usage: 'Invokes ProviderAdapter generateStream method.',
    safety: 'Enforce response token limits to prevent runaway generation.',
    permissions: 'Safe operation.',
    verification: 'Confirm stream terminates cleanly with stop reason (stop, tool_calls, length).',
    failure_handling: 'If stream drops or times out, retry with exponential backoff up to max_tool_retries.',
    output_contract: 'NormalizedInferenceResponse with text, toolCalls: array, tokenUsage: object.',
    examples: 'Streaming tokens from local Apple MLX inference engine.',
    related_skills: ['ai-llm', 'core-agent-runtime'],
  },
  {
    name: 'ai-training',
    version: '1.0.0',
    description: 'Coordinates model fine-tuning (LoRA, QLoRA), dataset formatting (JSONL), and training loss tracking.',
    category: 'ai',
    dir: 'training',
    risk: 'high',
    requires_permission: true,
    required_tools: ['shell_execute', 'read_file'],
    optional_tools: ['file_metadata'],
    fallbacks: 'Prepare training datasets and scripts for user execution.',
    title: 'Model Fine-Tuning & Training Supervision',
    purpose: 'Prepare instruction-tuning datasets, configure LoRA parameters, and monitor training checkpoints.',
    when_to_activate: 'Activate when fine-tuning coding models or preparing domain-specific adapters.',
    inputs: 'Dataset path (JSONL), base model identifier, LoRA rank/alpha, epochs, learning rate.',
    preconditions: 'Adequate GPU VRAM or Apple Silicon Unified Memory must be verified before launch.',
    procedure: `1. Validate dataset format: verify each line is valid JSON with prompt/completion.
2. MEMORY CHECK: Calculate required VRAM based on base model size, quantization, and batch size.
3. NEVER launch training without confirming memory fits within physical RAM.
4. Configure training hyperparameters (LoRA rank=16, alpha=32, lr=2e-4).
5. Execute training script via shell_execute with logging.
6. Monitor training loss across epochs; stop if loss diverges.`,
    tool_usage: 'Use read_file to inspect dataset; shell_execute for training runner.',
    safety: 'STRICT INVARIANT: Verify VRAM constraints before launch to prevent host freeze or OOM panics.',
    permissions: 'High risk operation; requires explicit confirmation.',
    verification: 'Check that final adapter checkpoint is saved and loss converges.',
    failure_handling: 'If CUDA OOM occurs, reduce batch size, enable gradient accumulation, or use 4-bit QLoRA.',
    output_contract: 'TrainingSummary with baseModel, adapterPath, finalLoss, epochsCompleted.',
    examples: 'Fine-tuning a 3B coding model with QLoRA on Apple Silicon using MLX.',
    related_skills: ['ai-evaluation', 'ai-mlx', 'ai-cuda'],
  },
  {
    name: 'ai-evaluation',
    version: '1.0.0',
    description: 'Evaluates model output quality, code pass@1 accuracy, latency benchmarks, and schema compliance.',
    category: 'ai',
    dir: 'evaluation',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['shell_execute'],
    optional_tools: ['read_file'],
    fallbacks: 'Execute standard ToolBench benchmark locally.',
    title: 'Model Quality & Benchmark Evaluation',
    purpose: 'Measure model coding capabilities, schema adherence accuracy, TTFT, and token throughput.',
    when_to_activate: 'Activate when benchmarking model adapters, comparing local runtimes, or testing fine-tuned checkpoints.',
    inputs: 'Target model, evaluation dataset or benchmark suite (ToolBench, HumanEval, TTFT).',
    preconditions: 'Model provider must be online.',
    procedure: `1. Load evaluation test cases (e.g. benchmarks/index.ts).
2. Execute model prompts sequentially or in controlled batches.
3. Measure Time-to-First-Token (TTFT) and tokens-per-second throughput.
4. Evaluate schema accuracy: check if tool call arguments match JSON schema definitions.
5. Execute generated code tests to measure functional correctness (pass@1).
6. Compile benchmark report.`,
    tool_usage: 'Invoke tsx benchmarks/index.ts via shell_execute.',
    safety: 'Run evaluated code in isolated sandboxes to prevent test execution side effects.',
    permissions: 'Safe benchmarking evaluation.',
    verification: 'Confirm benchmark assertions pass within target latency and accuracy budgets.',
    failure_handling: 'If evaluation fails to parse outputs, record exact raw response for failure analysis.',
    output_contract: 'ModelBenchmarkReport with accuracyPercent, ttftMs, tokensPerSec, memoryMb.',
    examples: 'Evaluating ToolBench schema accuracy (100%) and startup latency (25ms).',
    related_skills: ['ai-llm', 'data-data-analysis'],
  },
  {
    name: 'ai-huggingface',
    version: '1.0.0',
    description: 'Interacts with Hugging Face Hub, model checkpoints, serverless inference API, and tokenizers.',
    category: 'ai',
    dir: 'huggingface',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['http_request'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Query Hugging Face model cards via web-open.',
    title: 'Hugging Face Hub & Serverless Integration',
    purpose: 'Discover model weights, download GGUF/Safetensors checkpoints, and use Serverless Inference API.',
    when_to_activate: 'Activate when querying Hugging Face repositories or using HF Serverless models (<10B free).',
    inputs: 'Model repository ID (e.g. Qwen/Qwen2.5-Coder-7B-Instruct), task.',
    preconditions: 'HF token configured in AuthStore for authenticated calls.',
    procedure: `1. Query Hugging Face Hub API to retrieve model card metadata, files, and tags.
2. Inspect model architecture, quantization variants (Q4_K_M, Q8_0), and file sizes.
3. If downloading: obtain direct resolve/main download URL for target file.
4. If invoking Serverless API: send request with authorization header.
5. Normalize response tokens and return output.`,
    tool_usage: 'Invoke http_request against huggingface.co API.',
    safety: 'Verify model hash before loading external checkpoints to prevent code execution via pickle.',
    permissions: 'Safe read-only network operation.',
    verification: 'Confirm model repository exists and serverless API returns valid completion.',
    failure_handling: 'If HF returns 503 (model loading), wait and retry with exponential backoff.',
    output_contract: 'HuggingFaceModelDetails with repoId, pipelineTag, downloads, availableGgufFiles: array.',
    examples: 'Querying Hugging Face for available GGUF quantizations of DeepSeek-Coder.',
    related_skills: ['ai-llm', 'network-downloads'],
  },
  {
    name: 'ai-ollama',
    version: '1.0.0',
    description: 'Integrates with local Ollama daemon (127.0.0.1:11434), model pulling, and streaming inference.',
    category: 'ai',
    dir: 'ollama',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['http_request'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Check if Ollama service is running via curl 127.0.0.1:11434.',
    title: 'Ollama Local Daemon Integration',
    purpose: 'Discover installed local models, pull new weights, and route offline inference to Ollama.',
    when_to_activate: 'Activate when running in offline or private local model mode.',
    inputs: 'Model tag (e.g. qwen2.5-coder:7b), prompt messages, stream flag.',
    preconditions: 'Ollama daemon must be running at 127.0.0.1:11434.',
    procedure: `1. Ping http://127.0.0.1:11434/api/tags using http_request to verify service health.
2. List locally pulled models and check if target model is present.
3. If model is missing and user authorized pull: trigger /api/pull stream.
4. Send chat completion request to http://127.0.0.1:11434/api/chat.
5. Stream tokens through ResponseNormalizer.
6. Return completed response.`,
    tool_usage: 'Call http_request to Ollama REST endpoints.',
    safety: 'Check host available RAM before pulling models >= 14B parameters.',
    permissions: 'Requires local network permission.',
    verification: 'Confirm Ollama daemon is reachable and responds with model list.',
    failure_handling: 'If connection refused, alert user to launch Ollama application (ollama serve).',
    output_contract: 'OllamaStatus with running: boolean, models: string[], activeModel: string.',
    examples: 'Routing coding task to local qwen2.5-coder:7b on Ollama.',
    related_skills: ['ai-llm', 'ai-inference'],
  },
  {
    name: 'ai-mlx',
    version: '1.0.0',
    description: 'Apple Silicon MLX native acceleration, Metal GPU unified memory allocation, and 4-bit quantization.',
    category: 'ai',
    dir: 'mlx',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['diagnostics_run'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Fall back to llama.cpp GGUF inference if MLX is not installed.',
    title: 'Apple Silicon MLX Native Acceleration',
    purpose: 'Maximize Apple Silicon M-series GPU throughput using MLX native unified memory execution.',
    when_to_activate: 'Activate on macOS arm64 when running local models natively.',
    inputs: 'Model weight path or Hugging Face repo (mlx-community/*), quantization mode.',
    preconditions: 'macOS arm64 platform with Apple Silicon chip (M1/M2/M3/M4).',
    procedure: `1. Call diagnostics_run to verify Apple Silicon ARM64 architecture and Unified Memory budget.
2. Check available allocatable memory: ensure model size < 70% of unified memory.
3. Load MLX model using 4-bit or 8-bit quantization.
4. Execute Metal-accelerated inference with unified memory zero-copy tensors.
5. Track generation tokens/sec and memory RSS.`,
    tool_usage: 'Operates through MLXProvider in @berkelium/providers.',
    safety: 'Do not allocate models exceeding unified memory limits to prevent macOS kernel memory compression freeze.',
    permissions: 'Safe local acceleration.',
    verification: 'Verify that MLX generation achieves expected throughput (>30 tokens/sec on M4).',
    failure_handling: 'If MLX package is missing, fall back to GGUF engine or suggest pip install mlx-lm.',
    output_contract: 'MlxRuntimeInfo with chipModel, unifiedMemoryGb, allocatableBudgetGb, status.',
    examples: 'Running berkelium-coder:3b natively on Apple Silicon M4 Max via MLX.',
    related_skills: ['ai-inference', 'terminal-diagnostics'],
  },
  {
    name: 'ai-cuda',
    version: '1.0.0',
    description: 'NVIDIA CUDA acceleration, nvidia-smi diagnostics, TensorRT-LLM, and VRAM memory constraints.',
    category: 'ai',
    dir: 'cuda',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['shell_execute'],
    optional_tools: [],
    fallbacks: 'Fall back to CPU execution if NVIDIA GPU is unavailable.',
    title: 'NVIDIA CUDA Acceleration & VRAM Management',
    purpose: 'Monitor NVIDIA GPUs, query VRAM allocation, and configure CUDA runtime environments.',
    when_to_activate: 'Activate when executing on Linux/Windows hosts with NVIDIA GPUs or remote GPU instances.',
    inputs: 'CUDA device ID, VRAM allocation request.',
    preconditions: 'NVIDIA driver and CUDA runtime installed.',
    procedure: `1. Execute nvidia-smi --query-gpu=name,memory.total,memory.free,driver_version --format=csv via shell_execute.
2. Parse available free VRAM.
3. Compute whether model weights + KV cache fit inside free VRAM.
4. Set CUDA_VISIBLE_DEVICES to designate target GPU.
5. Return GPU status report.`,
    tool_usage: 'Invoke shell_execute with nvidia-smi.',
    safety: 'NEVER launch GPU tasks that exceed free VRAM, as it causes CUDA Out-Of-Memory kernel panics.',
    permissions: 'Safe hardware inspection.',
    verification: 'Confirm nvidia-smi reports valid GPU name, driver version, and free VRAM.',
    failure_handling: 'If nvidia-smi fails or is absent, report no CUDA hardware detected.',
    output_contract: 'CudaGpuStatus with gpuName, totalVramMb, freeVramMb, driverVersion.',
    examples: 'Checking free VRAM on NVIDIA RTX 4090 before loading a 14B model.',
    related_skills: ['ai-inference', 'terminal-diagnostics'],
  },
  {
    name: 'ai-rocm',
    version: '1.0.0',
    description: 'AMD ROCm GPU acceleration, rocm-smi diagnostics, HIP runtime, and Radeon memory allocation.',
    category: 'ai',
    dir: 'rocm',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['shell_execute'],
    optional_tools: [],
    fallbacks: 'Fall back to CPU execution if ROCm is absent.',
    title: 'AMD ROCm Acceleration & Diagnostics',
    purpose: 'Manage AMD Radeon / Instinct GPUs, verify ROCm HIP runtime, and inspect VRAM allocation.',
    when_to_activate: 'Activate when running local models on AMD GPU hardware.',
    inputs: 'ROCm device ID, memory request.',
    preconditions: 'AMD ROCm drivers installed.',
    procedure: `1. Execute rocm-smi --showid --showmeminfo vram via shell_execute.
2. Extract available VRAM for AMD graphics cards.
3. Verify HIP_VISIBLE_DEVICES environment configuration.
4. Check compatibility with PyTorch ROCm or llama.cpp ROCm backend.
5. Return AMD hardware status.`,
    tool_usage: 'Call shell_execute with rocm-smi.',
    safety: 'Ensure adequate VRAM headroom to avoid hardware crash.',
    permissions: 'Safe hardware inspection.',
    verification: 'Confirm rocm-smi outputs valid device and memory details.',
    failure_handling: 'If rocm-smi is missing, report ROCm runtime not installed.',
    output_contract: 'RocmStatus with deviceName, vramFreeMb, vramTotalMb.',
    examples: 'Checking VRAM availability on AMD Radeon 7900 XTX.',
    related_skills: ['ai-cuda', 'terminal-diagnostics'],
  },
];
