import { SkillDefinition } from './types.js';

export const browserSkills: SkillDefinition[] = [
  {
    name: 'browser-navigation',
    version: '1.0.0',
    description: 'Navigates headless browser to web addresses, manages redirects, cookies, and history.',
    category: 'browser',
    dir: 'navigation',
    risk: 'low',
    requires_permission: true,
    required_tools: ['browser_navigate'],
    optional_tools: ['browser_inspect'],
    fallbacks: 'Use web_open for static HTTP document fetching.',
    title: 'Headless Browser Navigation',
    purpose: 'Drive headless Chrome/Chromium sessions, navigate to URLs, handle timeouts and redirects.',
    when_to_activate: 'Activate when interacting with client-rendered applications or multi-step web workflows.',
    inputs: 'Target URL, timeout_ms (default 30000), waitUntil (load, domcontentloaded, networkidle).',
    preconditions: 'Browser automation server (Playwright or Chrome DevTools MCP) must be running.',
    procedure: `1. Sanitize target URL and check network permissions.
2. Initialize or reuse active browser page.
3. Call browser_navigate with URL and waitUntil strategy.
4. Verify HTTP status is 200/300 range.
5. Capture loaded page title and final URL.`,
    tool_usage: 'Invoke browser_navigate with url.',
    safety: 'Block navigation to file:///, 169.254.169.254, or internal loopback ports without permission.',
    permissions: 'Requires browser navigation permission.',
    verification: 'Confirm browser page loads and returns HTTP 200.',
    failure_handling: 'If page times out, retry with domcontentloaded or fall back to web_open.',
    output_contract: 'NavigationResult with finalUrl, httpStatus, title, durationMs.',
    examples: 'Navigating browser to local dev server http://localhost:3000 to test web app.',
    related_skills: ['browser-page-inspection', 'browser-interaction', 'web-browser'],
  },
  {
    name: 'browser-page-inspection',
    version: '1.0.0',
    description: 'Inspects rendered DOM elements, accessibility trees, computed styles, and text content.',
    category: 'browser',
    dir: 'page-inspection',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['browser_inspect'],
    optional_tools: ['browser_screenshot'],
    fallbacks: 'Extract page text via web_open.',
    title: 'DOM & Accessibility Tree Inspection',
    purpose: 'Examine rendered DOM nodes, ARIA roles, input form fields, and text content.',
    when_to_activate: 'Activate after browser navigation before clicking or typing on interactive elements.',
    inputs: 'CSS selector (optional), accessibility snapshot flag.',
    preconditions: 'Browser page must be loaded.',
    procedure: `1. Call browser_inspect to retrieve the accessibility tree or DOM snippet.
2. Identify unique selectors or ARIA labels for interactive elements.
3. Verify that expected UI components (buttons, forms, headings) are rendered.
4. Extract text content or input values.
5. Return structured DOM representation.`,
    tool_usage: 'Invoke browser_inspect.',
    safety: 'Read-only inspection.',
    permissions: 'Safe read-only operation.',
    verification: 'Confirm inspection returns non-empty element tree.',
    failure_handling: 'If selector is not found, wait 1000ms for dynamic rendering or inspect parent element.',
    output_contract: 'PageInspectionResult with elements: array, textContent: string.',
    examples: 'Inspecting login form inputs and submit button on local web app.',
    related_skills: ['browser-navigation', 'browser-interaction'],
  },
  {
    name: 'browser-interaction',
    version: '1.0.0',
    description: 'Clicks buttons, types into input fields, selects dropdowns, and submits forms.',
    category: 'browser',
    dir: 'interaction',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['browser_click', 'browser_type'],
    optional_tools: ['browser_inspect'],
    fallbacks: 'Send direct HTTP POST payload if API is accessible.',
    title: 'Browser Element Interaction',
    purpose: 'Interact with rendered page controls (click, type, keypress, select) during E2E testing.',
    when_to_activate: 'Activate when testing interactive user workflows or submitting web forms.',
    inputs: 'Selector, interaction type (click, type), text to type (for type action).',
    preconditions: 'Target element must be visible and enabled in the DOM.',
    procedure: `1. Inspect target element using browser_inspect to confirm it is interactive.
2. If typing: invoke browser_type with selector and sanitized text.
3. If clicking: invoke browser_click with selector.
4. Wait for resulting network request or DOM mutation.
5. Verify resulting page state.`,
    tool_usage: 'Call browser_click and browser_type.',
    safety: 'NEVER submit financial transactions, password change forms, or unauthorized destructive actions.',
    permissions: 'Requires browser interaction capability.',
    verification: 'Confirm DOM updates or URL changes in response to the interaction.',
    failure_handling: 'If element is obscured or disabled, inspect overlay modals or wait for enablement.',
    output_contract: 'InteractionResult with action, selector, success: boolean, resultingUrl.',
    examples: 'Typing "search query" into search input and clicking submit button.',
    related_skills: ['browser-page-inspection', 'browser-screenshots'],
  },
  {
    name: 'browser-screenshots',
    version: '1.0.0',
    description: 'Captures full-page or element-level screenshots for visual regression and verification.',
    category: 'browser',
    dir: 'screenshots',
    risk: 'low',
    requires_permission: true,
    required_tools: ['browser_screenshot'],
    optional_tools: ['file_metadata'],
    fallbacks: 'Rely on text DOM inspection if image capture is disabled.',
    title: 'Visual Screenshot Capture & Verification',
    purpose: 'Capture visual artifacts of rendered web applications for regression review and user verification.',
    when_to_activate: 'Activate when validating frontend UI changes, layout responsiveness, or bug visual evidence.',
    inputs: 'Output image path, fullPage flag (boolean), element selector (optional).',
    preconditions: 'Browser page must be fully rendered.',
    procedure: `1. Verify target directory for screenshot exists in workspace or artifacts.
2. Invoke browser_screenshot with destination path and fullPage options.
3. Verify that image was saved to disk and has valid PNG/JPEG dimensions.
4. Embed screenshot path into walkthrough or verification report.
5. Return screenshot artifact path.`,
    tool_usage: 'Invoke browser_screenshot with path.',
    safety: 'Ensure screenshot does not capture sensitive user data or credentials displayed on screen.',
    permissions: 'Requires filesystem write permission.',
    verification: 'Verify image file exists on disk with non-zero size.',
    failure_handling: 'If capture fails, check page dimensions and viewport configuration.',
    output_contract: 'ScreenshotResult with filePath, width, height, sizeBytes.',
    examples: 'Capturing full-page screenshot of rendered dashboard for walkthrough report.',
    related_skills: ['browser-page-inspection', 'core-verification'],
  },
  {
    name: 'browser-browser-debugging',
    version: '1.0.0',
    description: 'Inspects browser console errors, failed network requests (HTTP 4xx/5xx), and client crashes.',
    category: 'browser',
    dir: 'browser-debugging',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['browser_inspect'],
    optional_tools: ['browser_evaluate'],
    fallbacks: 'Inspect server-side application logs.',
    title: 'Client-Side Browser Diagnostics & Debugging',
    purpose: 'Capture JavaScript console errors, uncaught exceptions, and failed network fetch calls.',
    when_to_activate: 'Activate when a web page displays a blank screen, crashes, or fails to fetch data.',
    inputs: 'Browser session context.',
    preconditions: 'Browser session must be active.',
    procedure: `1. Inspect browser console logs (console.error, console.warn).
2. Retrieve network activity log and identify failed requests (status >= 400).
3. Check for CORS errors or blocked script assets.
4. Extract stack traces of uncaught client-side exceptions.
5. Synthesize root cause and pass to code-debugging.`,
    tool_usage: 'Call browser_inspect with log filter.',
    safety: 'Read-only diagnostic inspection.',
    permissions: 'Safe operation.',
    verification: 'Confirm console errors accurately reflect client-side runtime behavior.',
    failure_handling: 'If console logs are empty, evaluate window.performance metrics or inspect DOM.',
    output_contract: 'BrowserDebugReport with consoleErrors: array, failedRequests: array, unhandledExceptions: array.',
    examples: 'Debugging "Uncaught TypeError: Cannot read properties of undefined" in React SPA.',
    related_skills: ['browser-page-inspection', 'code-debugging'],
  },
];
