import { SkillDefinition } from './types.js';

export const buildSkills: SkillDefinition[] = [
  {
    name: 'build-build',
    version: '1.0.0',
    description: 'Compiles monorepo packages, libraries, and CLI bundles across project targets.',
    category: 'build',
    dir: 'build',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['shell_execute'],
    optional_tools: ['file_metadata'],
    fallbacks: 'Build individual packages iteratively using local tsconfig or tsc.',
    title: 'Monorepo Build Orchestration',
    purpose: 'Compile TypeScript packages, bundle CLI binaries, and verify artifact outputs.',
    when_to_activate: 'Activate before testing, before packaging binaries, and during CI builds.',
    inputs: 'Build target or package filter, clean flag.',
    preconditions: 'Dependencies must be installed.',
    procedure: `1. Execute project build command (e.g. pnpm run build).
2. Monitor build progress across all packages in topological dependency order.
3. Verify that output artifacts (dist/index.js, dist/index.d.ts) are generated.
4. Ensure executable binaries have +x permissions.
5. Report build status and total compilation time.`,
    tool_usage: 'Invoke shell_execute with pnpm run build.',
    safety: 'Do not run untrusted build scripts with root privileges.',
    permissions: 'Requires shell execution permission.',
    verification: 'Check exit code is 0 and verify dist/ directories contain compiled artifacts.',
    failure_handling: 'If build fails, parse compiler error diagnostics and feed into code-debugging.',
    output_contract: 'BuildResult with status (success/failed), compiledPackages: string[], durationMs: number.',
    examples: 'Building all 14 workspace packages and apps/cli in BerkeliumCodex.',
    related_skills: ['build-type-check', 'build-package'],
  },
  {
    name: 'build-lint',
    version: '1.0.0',
    description: 'Runs static linters (ESLint, Oxlint, Biome, Flake8) to detect stylistic and code quality defects.',
    category: 'build',
    dir: 'lint',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['shell_execute'],
    optional_tools: ['read_file'],
    fallbacks: 'Perform syntactic review and TypeScript type checking.',
    title: 'Static Code Quality Linting',
    purpose: 'Enforce code style standards, identify dead code, and flag anti-patterns statically.',
    when_to_activate: 'Activate during code reviews, before commits, and in CI quality gates.',
    inputs: 'Lint target files or directory, fix flag.',
    preconditions: 'Linter configuration (e.g. eslint.config.js) must be present.',
    procedure: `1. Determine configured linter from package.json (e.g. pnpm run lint).
2. Execute linter via shell_execute.
3. Parse warnings and errors with file, line, and rule identifiers.
4. If --fix was specified, verify auto-fix modifications.
5. Return lint report.`,
    tool_usage: 'Call shell_execute with lint command.',
    safety: 'Review auto-fixes to ensure they do not introduce logic changes.',
    permissions: 'Safe read-only execution unless --fix is specified.',
    verification: 'Check that linter exits with code 0 and 0 errors.',
    failure_handling: 'If lint errors occur, isolate offending lines and apply code-editing.',
    output_contract: 'LintReport with errorCount, warningCount, issues: array.',
    examples: 'Running pnpm run lint on packages/agent.',
    related_skills: ['build-format', 'build-type-check'],
  },
  {
    name: 'build-format',
    version: '1.0.0',
    description: 'Enforces code formatting standards using Prettier, Biome, Black, or Rustfmt.',
    category: 'build',
    dir: 'format',
    risk: 'low',
    requires_permission: true,
    required_tools: ['shell_execute'],
    optional_tools: ['read_file'],
    fallbacks: 'Preserve existing file indentation and spacing conventions manually.',
    title: 'Automated Code Formatting',
    purpose: 'Standardize indentation, line wrapping, quotes, and semicolons across the repository.',
    when_to_activate: 'Activate after code editing or before committing changes.',
    inputs: 'Target files, check-only flag.',
    preconditions: 'Formatting tool or project style rules must be configured.',
    procedure: `1. Identify formatting configuration (.prettierrc, biome.json).
2. Execute formatting command (e.g. prettier --write <files>).
3. If check-only flag is set, run with --check to detect unformatted files.
4. Inspect git diff to verify formatting changes do not alter semantics.
5. Return formatted files count.`,
    tool_usage: 'Invoke shell_execute with format command.',
    safety: 'Never format entire repository without user consent, as it pollutes git blame.',
    permissions: 'Requires filesystem edit permission.',
    verification: 'Confirm formatter reports all files match style rules.',
    failure_handling: 'If formatter errors on syntax error, resolve syntax defect first.',
    output_contract: 'FormatResult with formattedFiles: string[], unformattedCount: number.',
    examples: 'Running prettier --write on newly created test file.',
    related_skills: ['build-lint', 'code-code-editing'],
  },
  {
    name: 'build-type-check',
    version: '1.0.0',
    description: 'Executes strict compiler type checking across monorepo project references.',
    category: 'build',
    dir: 'type-check',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['shell_execute'],
    optional_tools: ['read_file'],
    fallbacks: 'Inspect TypeScript syntax manually.',
    title: 'Strict Compiler Type Validation',
    purpose: 'Verify static types, interface contracts, and project references with zero compiler errors.',
    when_to_activate: 'Activate after any TypeScript modification and before running tests.',
    inputs: 'Workspace tsconfig path (e.g. ./tsconfig.json).',
    preconditions: 'TypeScript must be installed and tsconfig references configured.',
    procedure: `1. Run pnpm run typecheck (tsc -b ./tsconfig.json) via shell_execute.
2. Capture compiler diagnostics (error TSxxxx).
3. Extract file paths, line numbers, and expected vs received types.
4. Verify that all 15 workspace projects typecheck cleanly.
5. Return typecheck report.`,
    tool_usage: 'Call shell_execute with tsc -b command.',
    safety: 'Read-only compilation validation.',
    permissions: 'Safe operation.',
    verification: 'Confirm tsc exits with code 0 and outputs no errors.',
    failure_handling: 'If type errors occur, feed TS error codes into code-debugging.',
    output_contract: 'TypeCheckResult with passed: boolean, errorCount: number, errors: string[].',
    examples: 'Validating composite TypeScript build: pnpm run typecheck.',
    related_skills: ['build-build', 'core-verification', 'code-debugging'],
  },
  {
    name: 'build-package',
    version: '1.0.0',
    description: 'Packages binaries, npm tarballs, wheel archives, or container artifacts.',
    category: 'build',
    dir: 'package',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['shell_execute'],
    optional_tools: ['file_metadata'],
    fallbacks: 'Archive dist directories manually via tar or zip.',
    title: 'Artifact Packaging & Bundling',
    purpose: 'Produce distribution tarballs, CLI executable bundles, or standalone archive packages.',
    when_to_activate: 'Activate when preparing npm releases, binary distribution, or Docker images.',
    inputs: 'Target package directory, package format (tarball, binary, zip).',
    preconditions: 'Target package must be compiled cleanly.',
    procedure: `1. Confirm build and typecheck pass with exit code 0.
2. Run packaging command (e.g. pnpm pack or tsup bundle).
3. Inspect generated archive contents to verify inclusion of dist/ and exclusion of test files.
4. Check package size and verify it meets lightweight distribution budgets.
5. Return packaged artifact paths.`,
    tool_usage: 'Execute packaging command via shell_execute.',
    safety: 'Ensure secrets, local .env files, and dev configs are never packaged.',
    permissions: 'Requires filesystem write permission.',
    verification: 'Confirm generated package file exists and is readable.',
    failure_handling: 'If packaging fails, verify package.json files array and exports fields.',
    output_contract: 'PackageResult with artifactPath, sizeBytes, filesIncluded: string[].',
    examples: 'Packaging berkelium-skills.zip for distribution.',
    related_skills: ['build-build', 'build-release'],
  },
  {
    name: 'build-release',
    version: '1.0.0',
    description: 'Orchestrates version bumping, changelog generation, and tag publication.',
    category: 'build',
    dir: 'release',
    risk: 'high',
    requires_permission: true,
    required_tools: ['shell_execute', 'read_file', 'edit_file'],
    optional_tools: ['git_commit'],
    fallbacks: 'Prepare release changelog draft for manual publishing.',
    title: 'Release Engineering & Version Lifecycle',
    purpose: 'Coordinate semantic version bumps, changelog updates, release notes, and publication gates.',
    when_to_activate: 'Activate when publishing new releases or preparing release milestones.',
    inputs: 'Bump type (patch, minor, major) or target version string.',
    preconditions: 'All tests and benchmarks must pass; working tree must be clean.',
    procedure: `1. Verify all tests (pnpm test) and benchmarks (pnpm run bench) pass.
2. Confirm working tree is clean with git_status.
3. Update version field across package.json files.
4. Update CHANGELOG.md with date and release notes.
5. Create release commit and Git tag (e.g. v1.0.0).
6. Verify tag was created at HEAD.`,
    tool_usage: 'Use edit_file to update manifests, shell_execute to tag.',
    safety: 'NEVER publish a release without 100% green test pass and benchmark verification.',
    permissions: 'High risk operation; requires explicit user approval.',
    verification: 'Check that package versions match tag and changelog.',
    failure_handling: 'If pre-release checks fail, abort and revert version bump.',
    output_contract: 'ReleaseEngineeringResult with version, tag, changelogNotes, status.',
    examples: 'Preparing Berkelium Codex v1.0.0 release candidate.',
    related_skills: ['build-package', 'github-releases', 'core-verification'],
  },
];
