import { SkillDefinition } from './types.js';

export const dataSkills: SkillDefinition[] = [
  {
    name: 'data-json',
    version: '1.0.0',
    description: 'Parses, validates, formats, and transforms JSON and JSON5 data with strict schema validation.',
    category: 'data',
    dir: 'json',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['write_file', 'edit_file'],
    fallbacks: 'Use JSON.parse / JSON.stringify in Node.js runtime.',
    title: 'JSON Processing & Schema Validation',
    purpose: 'Inspect, query, format, and validate structured JSON documents and configuration files.',
    when_to_activate: 'Activate when manipulating package.json, tsconfig.json, JSON schemas, or API responses.',
    inputs: 'JSON file path or string, JSONPath query, schema validator.',
    preconditions: 'Target JSON must be valid or fixable.',
    procedure: `1. Read JSON file using read_file.
2. Parse JSON with precise error localization on syntax errors (line/column).
3. If schema is provided: validate JSON against Draft 2020-12 schema.
4. If query is provided: evaluate path expression and extract data.
5. If formatting: re-indent with 2 spaces preserving key order.`,
    tool_usage: 'Use read_file to load, write_file to save modified JSON.',
    safety: 'Prevent prototype pollution attacks when parsing untrusted JSON.',
    permissions: 'Safe read-only operation unless saving modifications.',
    verification: 'Confirm JSON parses cleanly with zero syntax errors.',
    failure_handling: 'On JSON parse failure, report exact line number and offending token.',
    output_contract: 'JsonProcessingResult with parsedData, isValid: boolean, errors: string[].',
    examples: 'Validating chat.schema.json against Draft 2020-12 schema rules.',
    related_skills: ['data-yaml', 'filesystem-edit-file'],
  },
  {
    name: 'data-yaml',
    version: '1.0.0',
    description: 'Parses, generates, and formats YAML configurations for GitHub Actions, Docker Compose, and skills.',
    category: 'data',
    dir: 'yaml',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['write_file', 'edit_file'],
    fallbacks: 'Parse frontmatter and standard YAML structures natively.',
    title: 'YAML Configuration Parsing & Generation',
    purpose: 'Work with YAML files including skill frontmatter, CI/CD workflows, and Kubernetes manifests.',
    when_to_activate: 'Activate when editing .github/workflows/*.yml, skill frontmatter, or docker-compose.yml.',
    inputs: 'YAML file path or content string.',
    preconditions: 'Target file must be accessible.',
    procedure: `1. Read YAML content using read_file.
2. Parse indentation hierarchy (2-space standard).
3. Validate YAML syntax and type mappings.
4. Extract targeted configuration blocks.
5. Return parsed object or serialized YAML string.`,
    tool_usage: 'Use read_file to inspect, edit_file to modify specific lines.',
    safety: 'Ensure indentation is strictly preserved to prevent semantic changes.',
    permissions: 'Safe read-only unless modifying files.',
    verification: 'Check that YAML parses back into expected data structures without syntax errors.',
    failure_handling: 'If indentation is malformed, report line number and expected indent level.',
    output_contract: 'YamlProcessingResult with data: object, yamlText: string.',
    examples: 'Parsing frontmatter metadata in SKILL.md files.',
    related_skills: ['data-json', 'infrastructure-github-actions'],
  },
  {
    name: 'data-csv',
    version: '1.0.0',
    description: 'Parses and analyzes tabular CSV and TSV data files with delimiter detection and headers.',
    category: 'data',
    dir: 'csv',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['write_file'],
    fallbacks: 'Parse CSV rows line-by-line with delimiter splitting.',
    title: 'CSV & Tabular Data Processing',
    purpose: 'Parse tabular datasets, extract column stats, filter rows, and format markdown tables.',
    when_to_activate: 'Activate when inspecting benchmark results, telemetry dumps, or data export files.',
    inputs: 'CSV file path, delimiter (comma, tab, semicolon), hasHeaders flag.',
    preconditions: 'CSV file must exist and be readable.',
    procedure: `1. Read CSV sample slice using read_file.
2. Detect delimiter (comma, tab, semicolon).
3. Parse header row and column names.
4. Stream and parse data rows, handling quoted fields containing commas.
5. Compute basic summary metrics (row count, numeric column means).
6. Return structured tabular object.`,
    tool_usage: 'Invoke read_file with line slicing.',
    safety: 'Do not load multi-gigabyte CSV files entirely into memory; process in slices.',
    permissions: 'Safe read-only operation.',
    verification: 'Verify parsed column counts are consistent across all rows.',
    failure_handling: 'If rows have inconsistent column counts, report line numbers of irregular rows.',
    output_contract: 'TabularData with columns: string[], rowCount: number, preview: array.',
    examples: 'Parsing benchmark latency logs from benchmarks/results.csv.',
    related_skills: ['data-data-analysis', 'data-json'],
  },
  {
    name: 'data-xml',
    version: '1.0.0',
    description: 'Parses and queries XML documents, JUnit test reports, and SVG graphics.',
    category: 'data',
    dir: 'xml',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['write_file'],
    fallbacks: 'Extract tags via regex matching.',
    title: 'XML Document & JUnit Report Processing',
    purpose: 'Parse XML configuration files (pom.xml, AndroidManifest.xml) and test result summaries (junit.xml).',
    when_to_activate: 'Activate when parsing JUnit test runner outputs or Maven/Android build files.',
    inputs: 'XML file path, XPath or tag name to query.',
    preconditions: 'XML file must be readable.',
    procedure: `1. Read XML file using read_file.
2. Parse XML DOM tree structure.
3. Query targeted nodes (e.g. <testsuite>, <dependency>).
4. Extract element attributes and text content.
5. Return structured node object.`,
    tool_usage: 'Call read_file.',
    safety: 'XXE Protection: Disable external entity resolution to prevent XML External Entity attacks.',
    permissions: 'Safe read-only operation.',
    verification: 'Confirm XML is well-formed with closing tags.',
    failure_handling: 'If XML is malformed, report unclosed tag or line syntax error.',
    output_contract: 'XmlParseResult with rootElement, attributes, children: array.',
    examples: 'Extracting test failure details from junit.xml report.',
    related_skills: ['testing-test-execution', 'data-json'],
  },
  {
    name: 'data-sqlite',
    version: '1.0.0',
    description: 'Queries and inspects SQLite database schemas, tables, indexes, and records.',
    category: 'data',
    dir: 'sqlite',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['shell_execute'],
    optional_tools: ['file_metadata'],
    fallbacks: 'Inspect raw database file metadata or use sqlite3 CLI.',
    title: 'SQLite Database Inspection & Querying',
    purpose: 'Examine SQLite database schemas, execute read-only queries, and verify table states.',
    when_to_activate: 'Activate when debugging local application databases, session stores, or cache files.',
    inputs: 'Database file path, SQL query string.',
    preconditions: 'Database file must exist and sqlite3 command or driver available.',
    procedure: `1. Verify database file exists and is a valid SQLite 3 file.
2. Check if SQL query is read-only (SELECT, PRAGMA).
3. If mutating query (UPDATE, DELETE), request explicit confirmation.
4. Execute query via sqlite3 CLI or driver.
5. Format query result rows as structured JSON or markdown table.`,
    tool_usage: 'Invoke sqlite3 via shell_execute.',
    safety: 'Enforce read-only mode by default; block destructive DROP/TRUNCATE without authorization.',
    permissions: 'Requires shell execution and database write permission for mutations.',
    verification: 'Confirm query returns valid rows and exit code 0.',
    failure_handling: 'If database is locked (busy), retry with timeout or inspect open processes.',
    output_contract: 'QueryResult with columns: string[], rows: array, executionTimeMs: number.',
    examples: 'Running PRAGMA table_info(sessions); on local session database.',
    related_skills: ['data-data-analysis', 'terminal-shell'],
  },
  {
    name: 'data-data-analysis',
    version: '1.0.0',
    description: 'Performs statistical analysis, aggregations, trend analysis, and benchmark metric evaluation.',
    category: 'data',
    dir: 'data-analysis',
    risk: 'safe',
    requires_permission: false,
    required_tools: [],
    optional_tools: ['read_file'],
    fallbacks: 'Compute statistical summaries using built-in arithmetic functions.',
    title: 'Statistical & Benchmark Data Analysis',
    purpose: 'Analyze latency percentiles (p50, p95, p99), token throughput, memory trends, and distributions.',
    when_to_activate: 'Activate when analyzing benchmark outputs, profiling memory logs, or comparing runtimes.',
    inputs: 'Numeric dataset or benchmark results array.',
    preconditions: 'Dataset must be provided or read from benchmark output.',
    procedure: `1. Parse numerical arrays (e.g. latency in ms, tokens/sec, memory in MB).
2. Calculate summary statistics: mean, median, min, max, standard deviation.
3. Compute percentiles: p50, p90, p95, p99.
4. Compare against established performance budgets.
5. Formulate recommendations for performance optimization.`,
    tool_usage: 'In-memory statistical computations.',
    safety: 'Safe mathematical analysis.',
    permissions: 'Safe operation.',
    verification: 'Verify statistical metrics are within mathematically valid bounds.',
    failure_handling: 'Handle empty datasets or NaN values by filtering invalid entries.',
    output_contract: 'AnalysisSummary with count, mean, median, p95, p99, min, max, budgetPass: boolean.',
    examples: 'Evaluating whether startup latency (25ms) satisfies the <150ms budget.',
    related_skills: ['data-csv', 'terminal-diagnostics'],
  },
];
