import { SkillDefinition } from './types.js';

export const filesystemSkills: SkillDefinition[] = [
  {
    name: 'filesystem-list-files',
    version: '1.0.0',
    description: 'Lists directory contents with file type identification and size attributes.',
    category: 'filesystem',
    dir: 'list-files',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['list_directory'],
    optional_tools: ['file_metadata'],
    fallbacks: 'Execute platform shell ls command via shell_execute if list_directory tool is unavailable.',
    title: 'Directory Listing & Inventory',
    purpose: 'Inspect directory hierarchies, discover repository structure, and locate project assets.',
    when_to_activate: 'Activate when exploring an unfamiliar codebase, scanning submodules, or inspecting output directories.',
    inputs: 'Target directory path (absolute or workspace-relative), recursive flag, ignore patterns.',
    preconditions: 'Target path must exist and resolve within the authorized workspace jail.',
    procedure: `1. Resolve target directory path relative to workspace root.
2. Verify path does not escape workspace boundaries.
3. Call list_directory with target path and filtering patterns.
4. Distinguish between subdirectories, regular files, symlinks, and binary artifacts.
5. Format and return structured listing.`,
    tool_usage: 'Invoke list_directory passing directory path and optional recursion flag.',
    safety: 'Path traversal attacks (e.g. ../../) must be blocked by the workspace jail.',
    permissions: 'Safe read-only operation.',
    verification: 'Confirm directory listing contains valid file names and entries.',
    failure_handling: 'If directory does not exist or is inaccessible, report ENOENT with suggested parent paths.',
    output_contract: 'Array of FileEntry objects containing name, path, type, and sizeBytes.',
    examples: 'Listing all source files in packages/agent/src.',
    related_skills: ['filesystem-read-file', 'filesystem-search-files'],
  },
  {
    name: 'filesystem-read-file',
    version: '1.0.0',
    description: 'Reads text file content safely with line slice constraints and binary detection.',
    category: 'filesystem',
    dir: 'read-file',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['file_metadata'],
    fallbacks: 'Use shell_execute with head/tail or cat commands if native tool is offline.',
    title: 'Safe File Content Inspection',
    purpose: 'Retrieve file contents with line range slicing, avoiding context window bloat.',
    when_to_activate: 'Activate before editing any file, analyzing source logic, or parsing configurations.',
    inputs: 'File path, start line (optional), end line (optional).',
    preconditions: 'Target file must exist and not be a binary executable or archive.',
    procedure: `1. Resolve file path against workspace root.
2. Verify target is within permitted workspace jail.
3. Check file metadata to ensure it is text, not binary.
4. Read specific slice or whole file (max 800 lines per call).
5. Return numbered lines or raw content.`,
    tool_usage: 'Invoke read_file with path, startLine, and endLine parameters.',
    safety: 'Do not read files larger than 1MB into model context without range slicing.',
    permissions: 'Safe read-only operation.',
    verification: 'Check that output content matches the requested line range.',
    failure_handling: 'If file is missing, suggest closest file match using search-files.',
    output_contract: 'String containing the requested file contents.',
    examples: 'Reading lines 1 to 50 of apps/cli/src/entrypoint.ts.',
    related_skills: ['filesystem-edit-file', 'code-code-search'],
  },
  {
    name: 'filesystem-write-file',
    version: '1.0.0',
    description: 'Creates new files or writes complete content with parent directory provisioning.',
    category: 'filesystem',
    dir: 'write-file',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['write_file'],
    optional_tools: ['read_file'],
    fallbacks: 'Write content using shell_execute redirection after explicit permission approval.',
    title: 'Atomic File Creation & Writing',
    purpose: 'Create new files or overwrite existing files cleanly with atomic directory creation.',
    when_to_activate: 'Activate when scaffolding new source files, writing new tests, or generating schemas.',
    inputs: 'Target file path, content string, overwrite boolean flag.',
    preconditions: 'Target path must reside inside the workspace root.',
    procedure: `1. Resolve target path and verify workspace boundaries.
2. If file already exists and overwrite is false, abort or prompt for confirmation.
3. Provision parent directories recursively if missing.
4. Write content atomically to disk.
5. Verify file was written and matches expected size.`,
    tool_usage: 'Invoke write_file with target path and content string.',
    safety: 'Never overwrite critical existing files without explicit user intent or prior backup.',
    permissions: 'Requires filesystem write permission.',
    verification: 'Perform read_file or check file stats to confirm content integrity.',
    failure_handling: 'If disk is write-protected or EACCES occurs, request elevated capability.',
    output_contract: 'Success confirmation with written byte count and target file path.',
    examples: 'Creating a new test file tests/unit/chat-schema.test.ts.',
    related_skills: ['filesystem-edit-file', 'filesystem-delete-file'],
  },
  {
    name: 'filesystem-edit-file',
    version: '1.0.0',
    description: 'Applies surgical, targeted string replacements to files preserving surrounding structure.',
    category: 'filesystem',
    dir: 'edit-file',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['edit_file', 'read_file'],
    optional_tools: ['git_diff'],
    fallbacks: 'Read full file, apply targeted replacement in memory, and rewrite via write_file.',
    title: 'Surgical Targeted File Editing',
    purpose: 'Modify existing code with exact target match replacement, never rewriting whole files needlessly.',
    when_to_activate: 'Activate when fixing bugs, inserting features, or updating configuration parameters.',
    inputs: 'Target file path, target content substring, replacement content substring.',
    preconditions: 'Target file must exist, and targetContent must match uniquely within the file.',
    procedure: `1. Read the target section of the file using read_file.
2. Identify unique target substring including indentation and whitespace.
3. Formulate replacement string preserving code conventions.
4. Call edit_file with target and replacement.
5. Verify that the diff is minimal and syntactically correct.`,
    tool_usage: 'Invoke edit_file with targetPath, targetContent, and replacementContent.',
    safety: 'Target string must be unique within the file to prevent unintended replacement.',
    permissions: 'Requires filesystem edit permission.',
    verification: 'Check git diff or read the edited lines to confirm proper modification.',
    failure_handling: 'If targetContent is not found or ambiguous, re-read file and specify a wider range.',
    output_contract: 'Diff or confirmation of updated lines.',
    examples: 'Replacing a broken regex pattern inside src/parser.ts.',
    related_skills: ['filesystem-read-file', 'code-code-editing', 'core-verification'],
  },
  {
    name: 'filesystem-delete-file',
    version: '1.0.0',
    description: 'Safely removes files with confirmation gates and dependency warnings.',
    category: 'filesystem',
    dir: 'delete-file',
    risk: 'destructive',
    requires_permission: true,
    required_tools: ['delete_file'],
    optional_tools: ['git_status'],
    fallbacks: 'Invoke shell rm command only when explicitly authorized by user.',
    title: 'Safe File Deletion & Cleanup',
    purpose: 'Delete obsolete or temporary files safely with explicit impact confirmation.',
    when_to_activate: 'Activate when cleaning up generated scratch files, obsolete tests, or dead code.',
    inputs: 'Target file path.',
    preconditions: 'Target must not be a critical root file (.git, package.json, AGENTS.md).',
    procedure: `1. Resolve file path and verify target is not a protected repository file.
2. Check if file is tracked in git and whether there are uncommitted changes.
3. Request explicit permission if file is significant.
4. Invoke delete_file.
5. Verify file no longer exists.`,
    tool_usage: 'Call delete_file with path.',
    safety: 'NEVER delete files recursively without individual confirmation.',
    permissions: 'Strict DESTRUCTIVE permission tier; requires user authorization.',
    verification: 'Confirm target file no longer exists on filesystem.',
    failure_handling: 'If file is locked or permission denied, abort and explain lock reason.',
    output_contract: 'Deletion confirmation object with path and status.',
    examples: 'Deleting a temporary scratch script scratch/debug.js.',
    related_skills: ['filesystem-write-file', 'git-status'],
  },
  {
    name: 'filesystem-move-file',
    version: '1.0.0',
    description: 'Renames or relocates files across directory hierarchies while preserving Git history.',
    category: 'filesystem',
    dir: 'move-file',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['move_file'],
    optional_tools: ['git_status'],
    fallbacks: 'Copy file to destination and delete source after verification.',
    title: 'File Relocation & Rename',
    purpose: 'Move files cleanly across directories, updating imports if code files are moved.',
    when_to_activate: 'Activate when reorganizing package structure or renaming files.',
    inputs: 'Source file path, destination file path.',
    preconditions: 'Source must exist; destination parent directory must exist or be created.',
    procedure: `1. Validate source and destination paths inside workspace.
2. Verify destination does not accidentally overwrite an unrelated file.
3. Execute move_file.
4. If in a Git repository, use git mv when appropriate.
5. Verify file presence at destination.`,
    tool_usage: 'Call move_file with source and destination paths.',
    safety: 'Ensure destination does not conflict with existing files.',
    permissions: 'Requires filesystem write permission.',
    verification: 'Verify destination exists and source is gone.',
    failure_handling: 'If move fails, roll back any created intermediate files.',
    output_contract: 'Move confirmation object with oldPath and newPath.',
    examples: 'Moving legacy config from config.json to .berkelium/config.json.',
    related_skills: ['filesystem-copy-file', 'code-refactoring'],
  },
  {
    name: 'filesystem-copy-file',
    version: '1.0.0',
    description: 'Duplicates files or templates across workspace locations.',
    category: 'filesystem',
    dir: 'copy-file',
    risk: 'low',
    requires_permission: true,
    required_tools: ['copy_file'],
    optional_tools: ['file_metadata'],
    fallbacks: 'Read source file and write to destination using write_file.',
    title: 'File Duplication & Template Cloning',
    purpose: 'Duplicate existing files, config templates, or fixtures without modifying source.',
    when_to_activate: 'Activate when bootstrapping new test suites from existing examples or cloning configs.',
    inputs: 'Source file path, destination file path, overwrite boolean.',
    preconditions: 'Source path must exist and be readable.',
    procedure: `1. Verify source file existence.
2. Check if destination exists; if so, verify overwrite flag.
3. Ensure parent directory of destination is created.
4. Execute copy_file.
5. Verify identical byte sizes between source and destination.`,
    tool_usage: 'Call copy_file with source and destination.',
    safety: 'Prevent circular copy loops when copying directories.',
    permissions: 'Requires filesystem write permission.',
    verification: 'Confirm destination file size matches source.',
    failure_handling: 'If copy fails due to disk space or permissions, report specific OS error.',
    output_contract: 'Copy confirmation object with byte count.',
    examples: 'Copying template.env to .env.local.',
    related_skills: ['filesystem-write-file', 'filesystem-move-file'],
  },
  {
    name: 'filesystem-search-files',
    version: '1.0.0',
    description: 'Searches for files across the workspace by filename glob pattern or extension.',
    category: 'filesystem',
    dir: 'search-files',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['search_files'],
    optional_tools: ['list_directory'],
    fallbacks: 'Use shell find or glob command via shell_execute.',
    title: 'Workspace File Pattern Search',
    purpose: 'Locate files matching specific patterns (e.g. *.test.ts, *.json, Dockerfile).',
    when_to_activate: 'Activate when looking for test suites, config files, or specific component files.',
    inputs: 'Glob pattern or filename substring, search root directory.',
    preconditions: 'Search root must resolve within the workspace.',
    procedure: `1. Sanitize glob pattern and resolve root directory.
2. Filter out ignored directories (node_modules, .git, dist).
3. Execute search_files.
4. Sort matching files by relevance and depth.
5. Return array of matched relative file paths.`,
    tool_usage: 'Invoke search_files with pattern and root path.',
    safety: 'Ensure search does not enter infinite recursion on recursive symlinks.',
    permissions: 'Safe read-only operation.',
    verification: 'Check that returned paths exist and match the search pattern.',
    failure_handling: 'If no files match, broaden pattern or check parent directory.',
    output_contract: 'Array of matching relative file paths.',
    examples: 'Finding all Vitest test files matching **/*.test.ts.',
    related_skills: ['filesystem-list-files', 'code-code-search'],
  },
  {
    name: 'filesystem-file-metadata',
    version: '1.0.0',
    description: 'Inspects file stats, permissions, timestamps, MIME types, and line counts.',
    category: 'filesystem',
    dir: 'file-metadata',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['file_metadata'],
    optional_tools: ['read_file'],
    fallbacks: 'Use shell stat command via shell_execute.',
    title: 'File Metadata & Stat Inspection',
    purpose: 'Retrieve detailed file system attributes including size, mode, timestamps, and line counts.',
    when_to_activate: 'Activate before reading large files or when validating executable bits on binaries.',
    inputs: 'File path.',
    preconditions: 'Target file path must exist.',
    procedure: `1. Resolve target path within workspace.
2. Retrieve file stat properties (size, mode, mtime, isFile, isDirectory).
3. Detect MIME type and line count for text files.
4. Check if executable bit (+x) is set.
5. Return structured metadata object.`,
    tool_usage: 'Invoke file_metadata with target path.',
    safety: 'Do not follow broken or dangling symlinks without reporting them.',
    permissions: 'Safe read-only operation.',
    verification: 'Verify that metadata attributes are non-null.',
    failure_handling: 'If file is missing, return ENOENT status.',
    output_contract: 'FileMetadata object with sizeBytes, lineCount, isExecutable, mtime.',
    examples: 'Checking if apps/cli/dist/bin/berkelium.js has executable permissions.',
    related_skills: ['filesystem-read-file', 'terminal-diagnostics'],
  },
];
