import { SkillDefinition } from './types.js';

export const frameworksSkills: SkillDefinition[] = [
  {
    name: 'frameworks-react',
    version: '1.0.0',
    description: 'React component architecture, hooks conventions, state management, and virtual DOM rendering.',
    category: 'frameworks',
    dir: 'react',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['shell_execute', 'edit_file'],
    fallbacks: 'Inspect package.json dependencies for react and react-dom.',
    title: 'React Component & Hooks Architecture',
    purpose: 'Guide React development: hooks rules, state colocation, memoization, and component testing.',
    when_to_activate: 'Activate when working on React applications (*.jsx, *.tsx, React web apps).',
    inputs: 'React component files, package.json.',
    preconditions: 'React dependencies must be installed.',
    procedure: `1. Check React version (e.g. React 18/19).
2. Validate Rules of Hooks: call hooks only at top level, never inside conditionals or loops.
3. Colocate state to the lowest common ancestor component to prevent unnecessary re-renders.
4. Use React.memo and useMemo only where profiling indicates performance bottlenecks.
5. Run component tests using React Testing Library or Vitest.`,
    tool_usage: 'Use read_file to inspect components; shell_execute for running test suites.',
    safety: 'Do not mutate component state directly; always use state setter functions.',
    permissions: 'Safe convention guidelines.',
    verification: 'Confirm component renders without React key warnings or hook errors.',
    failure_handling: 'If infinite re-render loop occurs, inspect useEffect dependency array.',
    output_contract: 'ReactAuditResult with reactVersion, hooksCompliant: boolean, componentCount.',
    examples: 'Auditing a React UI component for stale closures and missing useEffect dependencies.',
    related_skills: ['frameworks-nextjs', 'languages-typescript'],
  },
  {
    name: 'frameworks-nextjs',
    version: '1.0.0',
    description: 'Next.js App Router, Server Components (RSC), Client Components, SSR, and API routes.',
    category: 'frameworks',
    dir: 'nextjs',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Inspect next.config.js or app/ directory.',
    title: 'Next.js App Router & Server Components',
    purpose: 'Standardize Next.js architecture: React Server Components, Client boundaries ("use client"), and SSG.',
    when_to_activate: 'Activate when working in Next.js codebases (app/, pages/, next.config.js/ts).',
    inputs: 'Next.js route files, layouts, page components.',
    preconditions: 'Next.js project structure must be present.',
    procedure: `1. Determine routing paradigm (App Router app/ vs Pages Router pages/).
2. Enforce Server Component default: keep components on the server unless interactivity is required.
3. Explicitly mark interactive client components with "use client" directive at the top.
4. Validate server-side data fetching with fetch() caching options.
5. Run next build to verify static page generation and route compilation.`,
    tool_usage: 'Use read_file to inspect routes; shell_execute for next build.',
    safety: 'Never import server-only secrets or database clients into client components.',
    permissions: 'Safe convention guidelines.',
    verification: 'Confirm next build finishes with 0 route errors and valid manifest.',
    failure_handling: 'If "You are attempting to export a component with state" occurs, add "use client" directive.',
    output_contract: 'NextJsReport with routerType (app/pages), ssrStatus: boolean, buildPass: boolean.',
    examples: 'Validating server-side data fetching and metadata generation in Next.js App Router.',
    related_skills: ['frameworks-react', 'frameworks-nodejs'],
  },
  {
    name: 'frameworks-nodejs',
    version: '1.0.0',
    description: 'Node.js backend architectures, native modules, asynchronous I/O, streams, and cluster workers.',
    category: 'frameworks',
    dir: 'nodejs',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Inspect package.json engines field.',
    title: 'Node.js Backend & Core APIs',
    purpose: 'Govern Node.js server architectures, native fs/promises, stream pipelines, and buffer management.',
    when_to_activate: 'Activate when developing Node.js CLI tools, background workers, or backend microservices.',
    inputs: 'Node.js source files, package.json.',
    preconditions: 'Node.js 20+ runtime.',
    procedure: `1. Check Node.js version target in package.json engines (>= 20.0.0).
2. Utilize native node: namespace imports (node:fs, node:path, node:crypto).
3. Use streams and pipeline() for large file processing rather than reading whole buffers.
4. Ensure graceful process termination with process.on('SIGTERM', ...).
5. Run node validation suite to verify process health and memory footprint.`,
    tool_usage: 'Use read_file to inspect source; shell_execute to run scripts.',
    safety: 'Avoid synchronous blocking APIs (fs.readFileSync) inside high-concurrency request paths.',
    permissions: 'Safe convention guidelines.',
    verification: 'Confirm Node.js processes exit with code 0 on clean completion.',
    failure_handling: 'If EventEmitter memory leak warning occurs, ensure removeListener is called.',
    output_contract: 'NodeJsAuditResult with nodeVersion, memoryUsageMb, streamsCompliant: boolean.',
    examples: 'Architecting streaming NDJSON parser for Berkelium Codex chat protocol.',
    related_skills: ['languages-javascript', 'languages-typescript'],
  },
  {
    name: 'frameworks-fastapi',
    version: '1.0.0',
    description: 'FastAPI modern Python web APIs, Pydantic data schemas, dependency injection, and async routes.',
    category: 'frameworks',
    dir: 'fastapi',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Inspect main.py or app/api routes.',
    title: 'FastAPI & Pydantic Microservice Engineering',
    purpose: 'Standardize FastAPI services: type-annotated route parameters, Pydantic V2 models, and async handlers.',
    when_to_activate: 'Activate when working on FastAPI applications (*.py importing fastapi).',
    inputs: 'FastAPI route handlers, Pydantic schemas.',
    preconditions: 'FastAPI and uvicorn dependencies installed in active venv.',
    procedure: `1. Inspect app instantiation and route decorators (@app.get, @app.post).
2. Ensure request/response schemas inherit from pydantic.BaseModel with field validations.
3. Use dependency injection (Depends) for database sessions and authentication.
4. Ensure I/O bound database calls are declared with async def.
5. Run test suite using pytest with TestClient.`,
    tool_usage: 'Use read_file to inspect schemas; shell_execute for pytest.',
    safety: 'Validate all user inputs with Pydantic field constraints to prevent injection.',
    permissions: 'Safe convention guidelines.',
    verification: 'Confirm TestClient tests pass and OpenAPI schema (/docs) is valid.',
    failure_handling: 'If RequestValidationError occurs, verify client payload matches Pydantic schema.',
    output_contract: 'FastApiAuditResult with routesCount, pydanticVersion, openApiValid: boolean.',
    examples: 'Writing an async FastAPI endpoint returning structured inference metrics.',
    related_skills: ['languages-python', 'network-api'],
  },
  {
    name: 'frameworks-express',
    version: '1.0.0',
    description: 'Express.js middleware pipelines, routing controllers, error-handling middleware, and security (Helmet).',
    category: 'frameworks',
    dir: 'express',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Inspect server.js or app.ts.',
    title: 'Express.js Server & Middleware Architecture',
    purpose: 'Guide Express.js APIs: middleware ordering, centralized error handling, and security hardening.',
    when_to_activate: 'Activate when developing Express.js applications (*.js, *.ts using express).',
    inputs: 'Express app definitions, router controllers, middleware.',
    preconditions: 'Express package installed in dependencies.',
    procedure: `1. Inspect middleware pipeline ordering: body parsers -> auth -> routers -> error handlers.
2. Verify that security headers are enabled via helmet middleware.
3. Ensure CORS policies are explicitly scoped rather than wildcard (*).
4. Verify centralized error handling middleware: (err, req, res, next) is defined last.
5. Test routes using supertest or HTTP client.`,
    tool_usage: 'Use read_file to inspect routes; shell_execute for supertest.',
    safety: 'Never omit the error-handling middleware; prevent unhandled exceptions from crashing server.',
    permissions: 'Safe convention guidelines.',
    verification: 'Confirm supertest suite executes with 100% assertions passing.',
    failure_handling: 'If route hangs indefinitely, check if next() or res.send() was missed.',
    output_contract: 'ExpressAuditResult with middlewareCount, securityHardened: boolean, testStatus.',
    examples: 'Adding centralized error handling middleware to an Express REST API.',
    related_skills: ['frameworks-nodejs', 'network-api'],
  },
];
