import { SkillDefinition } from './types.js';

export const gitSkills: SkillDefinition[] = [
  {
    name: 'git-status',
    version: '1.0.0',
    description: 'Inspects Git working tree status, staged files, unstaged modifications, and untracked artifacts.',
    category: 'git',
    dir: 'status',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['git_status'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Execute git status --porcelain via shell_execute.',
    title: 'Git Working Tree Status Inspection',
    purpose: 'Examine current branch, staged files, modified files, and untracked entries.',
    when_to_activate: 'Activate before making commits, before running tests, and after editing files.',
    inputs: 'Working directory.',
    preconditions: 'Target directory must be inside an initialized Git repository.',
    procedure: `1. Call git_status on the workspace root.
2. Parse current branch name and upstream divergence (ahead/behind).
3. Identify staged, unstaged, and untracked changes.
4. Flag any unexpected tracked files (e.g. node_modules, secrets, .DS_Store).
5. Return structured status record.`,
    tool_usage: 'Invoke git_status.',
    safety: 'Safe read-only operation.',
    permissions: 'Safe read-only operation.',
    verification: 'Confirm Git status cleanly categorizes modified files.',
    failure_handling: 'If not a git repo, suggest running git init or bk init.',
    output_contract: 'GitStatusResult with branch, staged: string[], unstaged: string[], untracked: string[].',
    examples: 'Checking working tree status before staging commit.',
    related_skills: ['git-diff', 'git-commit'],
  },
  {
    name: 'git-diff',
    version: '1.0.0',
    description: 'Generates and analyzes unified diffs between working tree, index, or historical commits.',
    category: 'git',
    dir: 'diff',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['git_diff'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Execute git diff via shell_execute.',
    title: 'Git Diff Inspection & Verification',
    purpose: 'Review precise lines added, deleted, or modified to ensure minimal patch footprint.',
    when_to_activate: 'Activate after code editing, before committing, and during verification loops.',
    inputs: 'Target file path (optional), staged flag, commit comparison range.',
    preconditions: 'Repository must be in a Git workspace with modifications.',
    procedure: `1. Call git_diff with optional target path and staged flag.
2. Parse diff chunks (+ additions, - deletions).
3. Check that no accidental debug logs, comments, or secrets were introduced.
4. Verify diff matches the user intent without unintended side effects.
5. Return formatted unified diff.`,
    tool_usage: 'Call git_diff.',
    safety: 'Read-only inspection.',
    permissions: 'Safe operation.',
    verification: 'Ensure diff corresponds accurately to modified files.',
    failure_handling: 'If diff is empty, verify whether changes were staged or if files were saved.',
    output_contract: 'String containing standard unified diff output.',
    examples: 'Inspecting diff on packages/agent/src/runtime.ts.',
    related_skills: ['git-status', 'code-code-review', 'core-verification'],
  },
  {
    name: 'git-log',
    version: '1.0.0',
    description: 'Inspects commit history, author attribution, commit messages, and hash references.',
    category: 'git',
    dir: 'log',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['git_log'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Execute git log -n <limit> --oneline via shell_execute.',
    title: 'Git Commit History Inspection',
    purpose: 'Trace commit lineage, recent changes, commit messages, and author attributions.',
    when_to_activate: 'Activate when understanding recent codebase changes, tracking regressions, or writing changelogs.',
    inputs: 'Commit limit (default 10), file path filter, oneline flag.',
    preconditions: 'Repository must contain at least one commit.',
    procedure: `1. Call git_log with limit and optional file path filter.
2. Extract commit hash, author, timestamp, and message for each entry.
3. Trace commit progression to identify when regressions or features were introduced.
4. Return structured commit history array.`,
    tool_usage: 'Call git_log with limit parameter.',
    safety: 'Read-only inspection.',
    permissions: 'Safe operation.',
    verification: 'Confirm commits are returned in chronological order.',
    failure_handling: 'If repository has zero commits, report initial commit pending.',
    output_contract: 'Array of GitCommit objects with hash, author, date, message.',
    examples: 'Inspecting the last 5 commits on branch main.',
    related_skills: ['git-status', 'git-diff'],
  },
  {
    name: 'git-branch',
    version: '1.0.0',
    description: 'Lists, creates, switches, and manages local and tracking Git branches.',
    category: 'git',
    dir: 'branch',
    risk: 'low',
    requires_permission: true,
    required_tools: ['git_branch'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Execute git branch or git checkout -b via shell_execute.',
    title: 'Git Branch Creation & Navigation',
    purpose: 'Isolate feature work on dedicated branches without mutating trunk/main branch directly.',
    when_to_activate: 'Activate when starting a new feature, bug fix, or creating an experimental spike.',
    inputs: 'Branch action (list, create, switch, delete), branch name.',
    preconditions: 'Working tree should be clean before switching branches.',
    procedure: `1. Call git_status to ensure working directory is clean or changes are stashed.
2. If listing, call git_branch to list local and remote branches.
3. If creating, validate branch name adheres to conventions (e.g. feat/name, fix/name).
4. Create and switch to new branch using git_branch.
5. Verify current active branch matches target.`,
    tool_usage: 'Call git_branch with action and branchName.',
    safety: 'Do not delete branches with unmerged work without explicit user confirmation.',
    permissions: 'Requires git write capability for create/delete/switch.',
    verification: 'Confirm git_status shows active branch as the requested branch.',
    failure_handling: 'If branch already exists, switch to it or prompt for a different name.',
    output_contract: 'BranchOperationResult with activeBranch, branches: string[].',
    examples: 'Creating and switching to feat/chat-protocol.',
    related_skills: ['git-status', 'git-commit'],
  },
  {
    name: 'git-commit',
    version: '1.0.0',
    description: 'Stages modified files and authors conventional, descriptive Git commits.',
    category: 'git',
    dir: 'commit',
    risk: 'low',
    requires_permission: true,
    required_tools: ['git_commit'],
    optional_tools: ['git_status', 'git_diff'],
    fallbacks: 'Execute git add and git commit -m via shell_execute.',
    title: 'Conventional Git Commit Authoring',
    purpose: 'Stage verified modifications and create atomic, conventional commit messages.',
    when_to_activate: 'Activate after verified code modifications, bugfixes, or feature completions.',
    inputs: 'Commit message string, file paths to stage (optional, defaults to all modified).',
    preconditions: 'Changes must pass verification tests and linter before committing.',
    procedure: `1. Check git_status to review modified files.
2. Verify that no tracked secret files or temporary artifacts are being staged.
3. Formulate conventional commit message (type(scope): description e.g. feat(cli): ...).
4. Call git_commit with message and target files.
5. Verify new commit hash was created.`,
    tool_usage: 'Call git_commit with message and optional files array.',
    safety: 'Never commit secrets, API keys, credentials, or build output.',
    permissions: 'Requires git write permission.',
    verification: 'Confirm git_log shows the new commit at HEAD.',
    failure_handling: 'If commit fails due to pre-commit hook, inspect hook output, remediate, and retry.',
    output_contract: 'CommitResult with commitHash, branch, filesCommitted count.',
    examples: 'Committing fix for state machine transition validation.',
    related_skills: ['git-status', 'git-diff', 'core-verification'],
  },
  {
    name: 'git-merge',
    version: '1.0.0',
    description: 'Merges branches with fast-forward evaluation and conflict detection.',
    category: 'git',
    dir: 'merge',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['git_merge'],
    optional_tools: ['shell_execute', 'git_status'],
    fallbacks: 'Execute git merge <branch> via shell_execute.',
    title: 'Git Branch Merging',
    purpose: 'Integrate feature branch changes into target branch cleanly.',
    when_to_activate: 'Activate when incorporating approved feature work into main or developing release branches.',
    inputs: 'Source branch name, merge strategy.',
    preconditions: 'Working tree must be clean before initiating merge.',
    procedure: `1. Verify working tree is clean via git_status.
2. Ensure current branch is the intended target branch.
3. Call git_merge with source branch name.
4. Check if merge completed cleanly (Fast-Forward or Merge commit).
5. If merge conflicts arise, trigger git-conflict-resolution.`,
    tool_usage: 'Call git_merge with source branch.',
    safety: 'Never force merge without understanding divergence.',
    permissions: 'Requires git write permission.',
    verification: 'Verify that HEAD points to merged tree and git status is clean.',
    failure_handling: 'If conflicts occur, do not abort blindly; inspect conflicted files.',
    output_contract: 'MergeResult with status (clean/conflicted), mergedFiles: string[].',
    examples: 'Merging feat/chat-protocol into main.',
    related_skills: ['git-conflict-resolution', 'git-status'],
  },
  {
    name: 'git-rebase',
    version: '1.0.0',
    description: 'Rebases active branch onto upstream tracking branch for clean linear commit history.',
    category: 'git',
    dir: 'rebase',
    risk: 'high',
    requires_permission: true,
    required_tools: ['shell_execute'],
    optional_tools: ['git_status'],
    fallbacks: 'Abort rebase with git rebase --abort on error.',
    title: 'Git Linear History Rebase',
    purpose: 'Replay local commits on top of upstream branch to maintain linear history.',
    when_to_activate: 'Activate when updating a branch against origin/main before PR submission.',
    inputs: 'Upstream branch name (e.g. origin/main).',
    preconditions: 'Working tree must be clean; all local changes committed.',
    procedure: `1. Confirm clean working tree with git_status.
2. Execute git rebase <upstream> via shell_execute.
3. If clean: report success with rebased commit count.
4. If conflict occurs: pause and trigger git-conflict-resolution or abort if requested.`,
    tool_usage: 'Execute git rebase via shell_execute.',
    safety: 'NEVER rebase public shared branches that others are actively building on.',
    permissions: 'High risk operation; requires explicit user permission.',
    verification: 'Verify git log shows commits replayed linearly atop upstream.',
    failure_handling: 'If rebase conflicts are too complex, execute git rebase --abort safely.',
    output_contract: 'RebaseResult with status (success/aborted/conflicted).',
    examples: 'Rebasing local main onto origin/main.',
    related_skills: ['git-merge', 'git-conflict-resolution'],
  },
  {
    name: 'git-stash',
    version: '1.0.0',
    description: 'Temporarily stashes uncommitted changes to allow branch switching or clean testing.',
    category: 'git',
    dir: 'stash',
    risk: 'low',
    requires_permission: true,
    required_tools: ['shell_execute'],
    optional_tools: ['git_status'],
    fallbacks: 'Perform manual patch export via git diff > patch.diff.',
    title: 'Git Working Tree Stashing',
    purpose: 'Shelve uncommitted modifications safely and restore them later.',
    when_to_activate: 'Activate when needing a clean tree to test upstream or switch branches temporarily.',
    inputs: 'Stash action (push, pop, list, drop), message description.',
    preconditions: 'Uncommitted changes must exist in working tree.',
    procedure: `1. Check git_status to identify changes to stash.
2. Execute git stash push -m "description" via shell_execute.
3. Confirm working tree is now clean.
4. Perform required task (e.g. pull, switch branch).
5. When ready, execute git stash pop to restore shelved work.`,
    tool_usage: 'Execute git stash commands via shell_execute.',
    safety: 'Do not drop stashes without verifying their contents.',
    permissions: 'Requires git write permission.',
    verification: 'Confirm stash list contains the saved entry.',
    failure_handling: 'If stash pop causes conflicts, keep stash entry and enter conflict resolution.',
    output_contract: 'StashResult with stashId, action, status.',
    examples: 'Stashing WIP code to run clean benchmark comparisons.',
    related_skills: ['git-status', 'git-rollback'],
  },
  {
    name: 'git-conflict-resolution',
    version: '1.0.0',
    description: 'Detects conflict markers (<<<<<<<, =======, >>>>>>>) and surgically resolves three-way merges.',
    category: 'git',
    dir: 'conflict-resolution',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['read_file', 'edit_file', 'shell_execute'],
    optional_tools: ['git_status'],
    fallbacks: 'Prompt user with conflicted blocks for manual selection.',
    title: 'Three-Way Git Conflict Resolution',
    purpose: 'Parse conflict markers, analyze conflicting edits, and synthesize clean unified resolutions.',
    when_to_activate: 'Activate during git merge, rebase, or cherry-pick conflicts.',
    inputs: 'List of conflicted file paths.',
    preconditions: 'Repository must be in a conflicted merge or rebase state.',
    procedure: `1. Call git_status to identify all unmerged paths (both modified).
2. For each conflicted file: read file content using read_file.
3. Locate all conflict marker regions (<<<<<<< HEAD, =======, >>>>>>> branch).
4. Analyze the semantic intent of both changes.
5. Apply edit_file to replace the conflict region with the correct unified logic.
6. Run test suite to verify the resolution compiles and tests pass.
7. Stage resolved files with git add.`,
    tool_usage: 'Use read_file to inspect markers, edit_file to replace, shell_execute to stage.',
    safety: 'Ensure NO conflict markers (<<<<<<<, =======, >>>>>>>) remain in any file.',
    permissions: 'Requires filesystem edit permission.',
    verification: 'Verify with search_files that no conflict markers remain and tests pass.',
    failure_handling: 'If resolution breaks semantics, abort merge via git merge --abort.',
    output_contract: 'ConflictResolutionReport with resolvedFiles: string[], testStatus.',
    examples: 'Resolving conflicting package.json version updates.',
    related_skills: ['git-merge', 'git-rebase', 'code-code-editing'],
  },
  {
    name: 'git-rollback',
    version: '1.0.0',
    description: 'Safely undos accidental changes, reverts commits, and restores files without data loss.',
    category: 'git',
    dir: 'rollback',
    risk: 'destructive',
    requires_permission: true,
    required_tools: ['git_restore'],
    optional_tools: ['shell_execute', 'git_diff'],
    fallbacks: 'Create Git revert commit rather than hard resetting history.',
    title: 'Safe Git Rollback & Reversion',
    purpose: 'Revert uncommitted changes or create revert commits while protecting user work.',
    when_to_activate: 'Activate when a refactoring attempt fails irrecoverably or uncommitted edits are discarded.',
    inputs: 'Target file path or commit hash, rollback scope (file, working tree, commit).',
    preconditions: 'Target modifications must be inspected with git_diff before discarding.',
    procedure: `1. CRITICAL: Review git_diff of target changes before discarding anything.
2. If reverting a single file: call git_restore with target file path.
3. If reverting a committed change: execute git revert <hash> --no-edit to preserve history.
4. PROHIBITED: Never execute git reset --hard or git clean -fd without explicit user authorization.
5. Verify working tree status after rollback.`,
    tool_usage: 'Call git_restore or git revert via shell_execute.',
    safety: 'Require explicit user confirmation for any operation that permanently deletes uncommitted code.',
    permissions: 'Destructive tier; requires explicit confirmation.',
    verification: 'Confirm target files are restored to clean state.',
    failure_handling: 'If rollback fails, abort and report error.',
    output_contract: 'RollbackResult with restoredFiles: string[], status.',
    examples: 'Discarding failed experimental edits in scratch/test.js.',
    related_skills: ['git-status', 'git-diff', 'filesystem-delete-file'],
  },
];
