import { SkillDefinition } from './types.js';

export const githubSkills: SkillDefinition[] = [
  {
    name: 'github-repositories',
    version: '1.0.0',
    description: 'Interacts with GitHub repository metadata, clones, remotes, and branch protection rules.',
    category: 'github',
    dir: 'repositories',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['shell_execute'],
    optional_tools: ['http_request'],
    fallbacks: 'Use git remote -v commands locally.',
    title: 'GitHub Repository Management',
    purpose: 'Query remote repository metadata, fork relationships, default branch, and origin remotes.',
    when_to_activate: 'Activate when synchronizing with upstream repositories or configuring remotes.',
    inputs: 'Repository slug (owner/repo), remote name.',
    preconditions: 'gh CLI or GitHub API token must be configured if making authenticated calls.',
    procedure: `1. Inspect local git remotes via git remote -v.
2. Query repository metadata using gh repo view or GitHub API.
3. Check default branch name (e.g. main vs master).
4. Verify repository access permissions and visibility (public/private).
5. Return structured repository details.`,
    tool_usage: 'Execute gh repo view or curl against api.github.com.',
    safety: 'Do not clone or pull into non-empty directories without confirmation.',
    permissions: 'Safe read-only inspection.',
    verification: 'Confirm repository details contain valid owner, repo, and defaultBranch fields.',
    failure_handling: 'If gh is not authenticated, fall back to public unauthenticated GitHub API endpoints.',
    output_contract: 'RepositoryInfo with owner, name, defaultBranch, isPrivate, url.',
    examples: 'Inspecting metadata for enigmahacker/BerkeliumCodex.',
    related_skills: ['github-pull-requests', 'git-status'],
  },
  {
    name: 'github-issues',
    version: '1.0.0',
    description: 'Lists, inspects, comments on, and creates GitHub issues with structured triage tags.',
    category: 'github',
    dir: 'issues',
    risk: 'low',
    requires_permission: true,
    required_tools: ['shell_execute'],
    optional_tools: ['http_request'],
    fallbacks: 'Format issue content as local markdown for user review.',
    title: 'GitHub Issue Triage & Management',
    purpose: 'Interact with GitHub issues to fetch bug reproductions, feature requests, or add triage notes.',
    when_to_activate: 'Activate when resolving reported issues or filing new bug reports.',
    inputs: 'Issue number, title, body, labels, state filter (open/closed).',
    preconditions: 'gh CLI installed and authenticated, or GITHUB_TOKEN configured.',
    procedure: `1. Query issues via gh issue list or view.
2. Parse issue description, error logs, and reproduction steps.
3. If creating an issue: validate that title, body, and labels follow repository templates.
4. Call gh issue create or gh issue comment.
5. Return issue URL and identifier.`,
    tool_usage: 'Execute gh issue commands via shell_execute.',
    safety: 'Do not spam or post automated comments without user consent.',
    permissions: 'Requires network and GitHub write permission.',
    verification: 'Confirm issue status or comment was posted successfully.',
    failure_handling: 'If gh CLI is missing, output formatted markdown issue for manual posting.',
    output_contract: 'GitHubIssue with number, title, state, url.',
    examples: 'Fetching issue #42 to inspect crash reproduction details.',
    related_skills: ['github-pull-requests', 'code-debugging'],
  },
  {
    name: 'github-pull-requests',
    version: '1.0.0',
    description: 'Creates, inspects, checks out, and reviews GitHub Pull Requests adhering to templates.',
    category: 'github',
    dir: 'pull-requests',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['shell_execute', 'git_diff'],
    optional_tools: ['read_file'],
    fallbacks: 'Generate git patch or format PR markdown body locally.',
    title: 'GitHub Pull Request Management',
    purpose: 'Author and review PRs using .github/pull_request_template.md standards.',
    when_to_activate: 'Activate when submitting finished feature work or checking out PR branches for review.',
    inputs: 'PR title, body description, target branch, PR number (for checkout/review).',
    preconditions: 'Current branch must be pushed to remote or ready for pushing.',
    procedure: `1. Check .github/pull_request_template.md to load template checklist.
2. Review git_diff to ensure all changes match PR scope.
3. Verify that CI gates (tests, typecheck, benchmarks) pass locally.
4. Push branch to remote using git push origin <branch>.
5. Execute gh pr create with title and filled template body.
6. Return PR URL.`,
    tool_usage: 'Execute gh pr create/view/checkout via shell_execute.',
    safety: 'Ensure branch contains zero secrets or untracked test debris before opening PR.',
    permissions: 'Requires git push and GitHub write permission.',
    verification: 'Verify that PR is created and checks are triggered on GitHub.',
    failure_handling: 'If push is rejected, verify branch permissions and rebase on upstream.',
    output_contract: 'PullRequestInfo with number, url, headBranch, baseBranch.',
    examples: 'Opening PR for failure recovery engine using the repository PR template.',
    related_skills: ['git-commit', 'code-code-review', 'github-actions'],
  },
  {
    name: 'github-actions',
    version: '1.0.0',
    description: 'Inspects, triggers, and analyzes GitHub Actions CI/CD workflows and job run logs.',
    category: 'github',
    dir: 'actions',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['shell_execute'],
    optional_tools: ['read_file'],
    fallbacks: 'Inspect .github/workflows YAML files locally.',
    title: 'GitHub Actions Workflow Inspection',
    purpose: 'Monitor CI runs, download job logs for failing builds, and diagnose pipeline bottlenecks.',
    when_to_activate: 'Activate when CI fails on remote PRs or after pushing commits to GitHub.',
    inputs: 'Workflow name, run ID, branch filter.',
    preconditions: 'Repository must contain .github/workflows configurations.',
    procedure: `1. Query active workflow runs using gh run list.
2. If a run failed: retrieve failed job logs via gh run view <id> --log-failed.
3. Parse failing step, assertion, or compiler error.
4. Pass failure context directly into code-debugging skill.
5. Return workflow summary.`,
    tool_usage: 'Execute gh run commands via shell_execute.',
    safety: 'Read-only log inspection.',
    permissions: 'Safe operation.',
    verification: 'Confirm workflow status matches remote GitHub Actions dashboard.',
    failure_handling: 'If gh run fails to fetch logs, inspect workflow YAML files to run the commands locally.',
    output_contract: 'WorkflowRun with id, name, status, conclusion, failedSteps: string[].',
    examples: 'Checking CI status on commit 5ff6d00.',
    related_skills: ['infrastructure-ci-cd', 'code-debugging'],
  },
  {
    name: 'github-releases',
    version: '1.0.0',
    description: 'Drafts, authors, and inspects GitHub Releases with semantic tags and changelogs.',
    category: 'github',
    dir: 'releases',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['shell_execute', 'read_file'],
    optional_tools: [],
    fallbacks: 'Draft release notes as local markdown document.',
    title: 'GitHub Release & Tag Management',
    purpose: 'Package release tags, changelog summaries, and asset binaries for GitHub releases.',
    when_to_activate: 'Activate when publishing a new version tag (e.g. v1.0.0) or releasing binaries.',
    inputs: 'Release tag, release title, changelog notes, asset files.',
    preconditions: 'Version in package.json and CHANGELOG.md must match release tag.',
    procedure: `1. Read CHANGELOG.md to extract version notes.
2. Verify git status is clean and HEAD commit is tagged.
3. Author release notes highlighting breaking changes and new features.
4. Execute gh release create <tag> with notes and optional binary assets.
5. Return release URL.`,
    tool_usage: 'Call gh release create via shell_execute.',
    safety: 'Do not publish releases without confirming clean benchmark and test passes.',
    permissions: 'Requires GitHub release creation permission.',
    verification: 'Verify release URL is active and assets are attached.',
    failure_handling: 'If release already exists, update existing release or abort.',
    output_contract: 'ReleaseInfo with tag, url, assets: string[].',
    examples: 'Drafting GitHub release v1.0.0 for Berkelium Codex.',
    related_skills: ['build-release', 'code-documentation'],
  },
  {
    name: 'github-code-search',
    version: '1.0.0',
    description: 'Searches remote GitHub repositories for code patterns, API usages, and reference examples.',
    category: 'github',
    dir: 'code-search',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['shell_execute'],
    optional_tools: ['http_request'],
    fallbacks: 'Use web-search to find relevant public repository examples.',
    title: 'GitHub Remote Code Search',
    purpose: 'Find real-world implementations, open-source usage patterns, or upstream library examples.',
    when_to_activate: 'Activate when integrating an undocumented API or seeking reference implementations.',
    inputs: 'Query string, language filter, repository or organization filter.',
    preconditions: 'gh CLI with search extension or internet connectivity.',
    procedure: `1. Construct targeted search query with language: and repo: filters.
2. Execute gh search code <query> via shell_execute.
3. Parse matching repository names, file paths, and snippet lines.
4. Extract idiomatic usage patterns.
5. Return structured code search results.`,
    tool_usage: 'Execute gh search code via shell_execute.',
    safety: 'Treat remote code as reference; sanitize before incorporating into workspace.',
    permissions: 'Safe read-only network operation.',
    verification: 'Check that search results point to valid GitHub repository files.',
    failure_handling: 'If rate limited, fall back to local search or web search.',
    output_contract: 'Array of GitHubCodeMatch with repository, path, snippet.',
    examples: 'Searching GitHub for MLX multi-modal tensor streaming patterns.',
    related_skills: ['code-code-search', 'web-documentation-research'],
  },
];
