import { SkillDefinition } from './types.js';

export const languagesSkills: SkillDefinition[] = [
  {
    name: 'languages-python',
    version: '1.0.0',
    description: 'Python project conventions, virtual environments (venv, uv, poetry), pytest, and type hints.',
    category: 'languages',
    dir: 'python',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Inspect pyproject.toml or requirements.txt manually.',
    title: 'Python Engineering Conventions',
    purpose: 'Standardize Python development: virtual environments, package managers, linting (Ruff), and pytest.',
    when_to_activate: 'Activate when working in Python repositories (*.py, pyproject.toml, requirements.txt).',
    inputs: 'Python source files, dependency manifests.',
    preconditions: 'Python interpreter or virtual environment must exist.',
    procedure: `1. Detect package and virtual environment manager (uv, poetry, venv, conda).
2. Activate virtual environment or prefix commands with uv run / poetry run.
3. Verify type hints using mypy or pyright.
4. Run tests using pytest with coverage flags.
5. Format code adhering to PEP 8 using Ruff or Black.`,
    tool_usage: 'Use read_file to inspect Python code; shell_execute for pytest / ruff.',
    safety: 'Never run pip install globally; always enforce virtual environment isolation.',
    permissions: 'Safe convention guidelines.',
    verification: 'Confirm pytest runs with exit code 0 and mypy reports zero type errors.',
    failure_handling: 'If ModuleNotFoundError occurs, install missing dependency into active venv.',
    output_contract: 'PythonEnvironmentSummary with pythonVersion, venvType, testRunner.',
    examples: 'Running pytest tests/ -v in an isolated uv virtual environment.',
    related_skills: ['testing-test-execution', 'build-type-check'],
  },
  {
    name: 'languages-javascript',
    version: '1.0.0',
    description: 'JavaScript ECMAScript standards, Node.js runtimes, ESM vs CommonJS, and event loops.',
    category: 'languages',
    dir: 'javascript',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Inspect package.json "type" field.',
    title: 'JavaScript & Node.js Runtime Engineering',
    purpose: 'Govern JavaScript execution, ESM (import) vs CommonJS (require) boundaries, and async event loops.',
    when_to_activate: 'Activate when editing *.js, *.mjs, *.cjs files or Node.js backend services.',
    inputs: 'JavaScript source files, package.json.',
    preconditions: 'Node.js runtime must be installed.',
    procedure: `1. Check package.json "type" field ("module" vs CommonJS default).
2. Ensure consistent import/export syntax (do not mix require and import in same file).
3. Verify asynchronous Promise handling with async/await and try/catch.
4. Avoid unhandled promise rejections and event listener memory leaks.
5. Validate code using Node.js or test runner.`,
    tool_usage: 'Use read_file to inspect source, shell_execute to run node scripts.',
    safety: 'Do not use eval() or Function() constructor with untrusted user input.',
    permissions: 'Safe convention guidelines.',
    verification: 'Confirm node executes script without unhandled rejections.',
    failure_handling: 'If ReferenceError: require is not defined occurs, convert to ES module import syntax.',
    output_contract: 'JavaScriptValidation with moduleFormat (esm/cjs), nodeCompat: boolean.',
    examples: 'Converting CommonJS require calls to ES module imports in a package.',
    related_skills: ['languages-typescript', 'frameworks-nodejs'],
  },
  {
    name: 'languages-typescript',
    version: '1.0.0',
    description: 'TypeScript strict mode, composite monorepos, tsconfig project references, and type inference.',
    category: 'languages',
    dir: 'typescript',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Inspect tsconfig.json and tsconfig.base.json.',
    title: 'TypeScript Strict Mode & Composite Project Engineering',
    purpose: 'Enforce strict type safety, zero `any` types, composite build references, and clean declaration emissions.',
    when_to_activate: 'Activate when working on *.ts, *.tsx files across packages/ and apps/.',
    inputs: 'TypeScript source files, tsconfig.json.',
    preconditions: 'TypeScript compiler must be configured.',
    procedure: `1. Check tsconfig.json for strict: true, noImplicitAny: true, and composite: true.
2. Ensure interfaces and types are cleanly exported and imported with type modifiers.
3. Validate generic constraints and discriminated union patterns.
4. Run tsc -b ./tsconfig.json to verify composite project references.
5. Ensure emitted declarations (.d.ts) match implementation signatures.`,
    tool_usage: 'Use read_file to check definitions; shell_execute for tsc -b.',
    safety: 'Do not use `as any` type assertions to silence valid compiler warnings.',
    permissions: 'Safe convention guidelines.',
    verification: 'Confirm tsc -b exits with 0 errors.',
    failure_handling: 'If circular type reference occurs, extract shared interfaces into dedicated types.ts.',
    output_contract: 'TypeScriptStatus with compilerVersion, strictMode: boolean, errors: array.',
    examples: 'Validating discriminated union types for BerkeliumChatEvent.',
    related_skills: ['build-type-check', 'languages-javascript'],
  },
  {
    name: 'languages-rust',
    version: '1.0.0',
    description: 'Rust cargo workflows, borrow checker rules, zero-cost abstractions, clippy, and cargo test.',
    category: 'languages',
    dir: 'rust',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Inspect Cargo.toml manifests.',
    title: 'Rust Systems Programming & Cargo Toolchain',
    purpose: 'Guide Rust development: ownership semantics, error handling (Result/Option), clippy, and cargo tests.',
    when_to_activate: 'Activate when inspecting or building Rust code (*.rs, Cargo.toml).',
    inputs: 'Rust source files, Cargo.toml.',
    preconditions: 'Rust toolchain (cargo, rustc) must be installed.',
    procedure: `1. Inspect Cargo.toml for dependencies, features, and edition (e.g. 2021).
2. Verify idiomatic error handling: use ? operator and custom error enums instead of unwrap().
3. Run cargo check for rapid syntax and borrow checker validation.
4. Run cargo clippy --all-targets for linting.
5. Run cargo test to execute unit and integration test suites.`,
    tool_usage: 'Call shell_execute with cargo commands.',
    safety: 'Avoid unsafe blocks unless strictly required for FFI, with documented safety invariants.',
    permissions: 'Safe convention guidelines.',
    verification: 'Confirm cargo check and cargo test exit with code 0.',
    failure_handling: 'If borrow checker error E0502 occurs, restructure lifetimes or clone values.',
    output_contract: 'RustToolchainReport with rustcVersion, clippyClean: boolean, testPass: boolean.',
    examples: 'Running cargo test --package berkelium-core in a Rust workspace.',
    related_skills: ['build-build', 'testing-test-execution'],
  },
  {
    name: 'languages-go',
    version: '1.0.0',
    description: 'Go module conventions, goroutines, channel synchronization, go vet, and go test.',
    category: 'languages',
    dir: 'go',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Inspect go.mod and go.sum.',
    title: 'Go Language & Module Engineering',
    purpose: 'Standardize Go development: explicit error handling (if err != nil), goroutine safety, and testing.',
    when_to_activate: 'Activate when working in Go projects (*.go, go.mod).',
    inputs: 'Go source files, go.mod.',
    preconditions: 'Go compiler toolchain must be installed.',
    procedure: `1. Inspect go.mod for module path and Go version.
2. Verify explicit error checks on all function calls returning error.
3. Validate concurrency safety: ensure Mutex locks are paired with defer unlock.
4. Run go vet ./... to catch common programming defects.
5. Run go test -v -race ./... to test with race detector enabled.`,
    tool_usage: 'Use read_file to inspect code; shell_execute for go test.',
    safety: 'Always run tests with -race to detect data races.',
    permissions: 'Safe convention guidelines.',
    verification: 'Confirm go test passes with zero race condition detections.',
    failure_handling: 'If race condition detected, inspect shared variable access and add mutex guards.',
    output_contract: 'GoToolchainStatus with goVersion, vetClean: boolean, raceClean: boolean.',
    examples: 'Running go test -v -race ./... in a Go backend service.',
    related_skills: ['testing-test-execution', 'build-build'],
  },
  {
    name: 'languages-java',
    version: '1.0.0',
    description: 'Java language conventions, Maven and Gradle project builds, JUnit 5 testing, and JVM diagnostics.',
    category: 'languages',
    dir: 'java',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Inspect pom.xml or build.gradle files.',
    title: 'Java Enterprise & JVM Engineering',
    purpose: 'Govern Java development: Maven/Gradle lifecycles, JUnit 5 assertions, and JVM heap configurations.',
    when_to_activate: 'Activate when developing Java projects (*.java, pom.xml, build.gradle).',
    inputs: 'Java source files, build descriptors.',
    preconditions: 'JDK 17+ and Maven/Gradle wrapper must be present.',
    procedure: `1. Detect build tool (Maven mvnw vs Gradle gradlew).
2. Check JDK version compatibility.
3. Inspect package structure (src/main/java, src/test/java).
4. Run compilation: ./mvnw test-compile or ./gradlew testClasses.
5. Run unit tests using JUnit 5 runner.`,
    tool_usage: 'Invoke shell_execute with Maven or Gradle wrapper commands.',
    safety: 'Ensure build wrappers (mvnw/gradlew) are executed rather than unpinned global binaries.',
    permissions: 'Safe convention guidelines.',
    verification: 'Confirm build wrapper exits with BUILD SUCCESS.',
    failure_handling: 'If ClassNotFoundException occurs, verify dependency scopes in pom.xml.',
    output_contract: 'JavaBuildSummary with jdkVersion, buildTool, testResults.',
    examples: 'Running ./mvnw clean test in a Spring Boot application.',
    related_skills: ['build-build', 'testing-test-execution'],
  },
  {
    name: 'languages-cpp',
    version: '1.0.0',
    description: 'C/C++ modern standards (C++17/20), CMake build configuration, Clang-Tidy, and memory safety.',
    category: 'languages',
    dir: 'cpp',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Inspect CMakeLists.txt.',
    title: 'Modern C++ & Native Systems Engineering',
    purpose: 'Enforce modern C++ standards, RAII memory management, CMake configuration, and ASan sanitizers.',
    when_to_activate: 'Activate when working on native C/C++ projects, MLX native kernels, or llama.cpp bindings.',
    inputs: 'C/C++ source files (*.cpp, *.hpp, *.cc), CMakeLists.txt.',
    preconditions: 'C++ compiler (clang++, g++) and CMake must be available.',
    procedure: `1. Inspect CMakeLists.txt for target definitions and compiler flags.
2. Enforce RAII memory ownership: prefer std::unique_ptr and std::shared_ptr over raw pointers.
3. Configure build with AddressSanitizer (-fsanitize=address) to catch memory corruption.
4. Run build via cmake --build build.
5. Run CTest test runner to verify native test suite passes.`,
    tool_usage: 'Call shell_execute with cmake commands.',
    safety: 'Never disable memory sanitizers when testing native pointers or buffer mutations.',
    permissions: 'Safe convention guidelines.',
    verification: 'Confirm build succeeds and ASan reports 0 memory leaks or buffer overflows.',
    failure_handling: 'If segmentation fault occurs, inspect AddressSanitizer crash log for buffer bounds.',
    output_contract: 'CppBuildReport with compiler, cmakeTarget, asanStatus.',
    examples: 'Building and testing native Apple Metal C++ kernels for MLX.',
    related_skills: ['build-build', 'testing-test-execution'],
  },
  {
    name: 'languages-shell',
    version: '1.0.0',
    description: 'Portable POSIX and Bash scripting, ShellCheck static analysis, error trapping, and quote safety.',
    category: 'languages',
    dir: 'shell',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Review shell scripts for unquoted variables and missing set -euo pipefail.',
    title: 'Portable Shell & Bash Scripting',
    purpose: 'Author robust, portable shell scripts with strict error trapping (set -euo pipefail) and quotes.',
    when_to_activate: 'Activate when writing launcher scripts (bin/bk), CI scripts, or hook wrappers (*.sh).',
    inputs: 'Shell script files.',
    preconditions: 'Bash or POSIX sh environment.',
    procedure: `1. Include standard shebang (#!/usr/bin/env bash or #!/bin/sh).
2. Set strict error handling: set -euo pipefail.
3. Always double-quote variable expansions ("$VAR") to prevent word-splitting and glob expansion.
4. Handle symlink resolution cleanly using readlink loop.
5. Run ShellCheck (shellcheck script.sh) to detect portability and syntax flaws.`,
    tool_usage: 'Use read_file to inspect, shell_execute to run shellcheck.',
    safety: 'NEVER use rm -rf "$VAR" without verifying that $VAR is non-empty and not root /.',
    permissions: 'Safe convention guidelines.',
    verification: 'Confirm shellcheck reports zero warnings and script executes correctly under bash and zsh.',
    failure_handling: 'If script behaves inconsistently across macOS and Linux, replace Bash-specific syntax with POSIX.',
    output_contract: 'ShellScriptValidation with shellcheckClean: boolean, portable: boolean.',
    examples: 'Authoring bin/bk with robust symlink resolution for global CLI usage.',
    related_skills: ['terminal-shell', 'build-lint'],
  },
];
