import { SkillDefinition } from './types.js';

export const securitySkills: SkillDefinition[] = [
  {
    name: 'security-security-audit',
    version: '1.0.0',
    description: 'Scans workspace, commits, and dependencies for vulnerabilities, misconfigurations, and unsafe patterns.',
    category: 'security',
    dir: 'security-audit',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['search_files'],
    optional_tools: ['shell_execute', 'read_file'],
    fallbacks: 'Scan files manually using regex patterns for common security vulnerabilities.',
    title: 'Workspace Security Audit & Vulnerability Scan',
    purpose: 'Conduct comprehensive security audits detecting injection flaws, insecure dependencies, and misconfigurations.',
    when_to_activate: 'Activate on bk scan security, before releases, or when auditing PR contributions.',
    inputs: 'Workspace root path, audit scope (secrets, dependencies, code, git).',
    preconditions: 'Workspace must be accessible.',
    procedure: `1. Run SecurityScanner across all workspace files.
2. Scan for hardcoded credentials (API keys, private keys, passwords).
3. Check for path traversal vulnerabilities and unsafe command execution patterns.
4. Scan dependency manifests for known CVEs or supply-chain advisories.
5. Compile vulnerability findings with severity ratings (CRITICAL, HIGH, MEDIUM, LOW).
6. Provide concrete remediation steps for every finding.`,
    tool_usage: 'Invoke search_files and SecurityScanner.',
    safety: 'Never display unmasked raw secrets in the audit report.',
    permissions: 'Safe read-only audit.',
    verification: 'Confirm all discovered issues have severity, file location, and remediation guidance.',
    failure_handling: 'If scanner errors on binary files, exclude binaries and continue scan.',
    output_contract: 'SecurityAuditReport with totalIssues, criticalCount, highCount, findings: array.',
    examples: 'Running bk scan security in BerkeliumCodex root.',
    related_skills: ['security-secrets', 'security-dependency-security', 'security-threat-modeling'],
  },
  {
    name: 'security-secrets',
    version: '1.0.0',
    description: 'Detects and redacts secrets (API keys, tokens, passwords, private keys) from logs and outputs.',
    category: 'security',
    dir: 'secrets',
    risk: 'safe',
    requires_permission: false,
    required_tools: [],
    optional_tools: ['read_file'],
    fallbacks: 'Apply regex redaction for common key formats (sk-*, ghp_*, eyJ*).',
    title: 'Secret Detection & Automatic Redaction',
    purpose: 'Prevent sensitive tokens, private keys, passwords, and credentials from leaking into model prompts or UI logs.',
    when_to_activate: 'Activate automatically on every model prompt layer, tool output, and log record.',
    inputs: 'Raw text buffer or stream.',
    preconditions: 'SecretDetector and SecretRedactor must be active in tool pipeline.',
    procedure: `1. Scan text buffer against high-entropy regex patterns (OpenAI sk-, GitHub ghp_, JWTs, AWS keys).
2. Identify private key blocks (-----BEGIN PRIVATE KEY-----).
3. If secret is detected, replace with redacted placeholder (e.g. [REDACTED_API_KEY_...]).
4. Emit secret_detected event if an active secret was found in source files.
5. Return sanitized text string.`,
    tool_usage: 'Operates via SecretRedactor in @berkelium/permissions.',
    safety: 'NEVER disable secret redaction in production or logging pipelines.',
    permissions: 'Safe in-memory redaction.',
    verification: 'Check that sanitized output contains zero raw credential substrings.',
    failure_handling: 'If pattern is uncertain, err on the side of caution and redact.',
    output_contract: 'RedactedOutput with sanitizedText: string, secretsRedactedCount: number.',
    examples: 'Redacting an accidentally logged Groq API key in tool stdout.',
    related_skills: ['security-security-audit', 'terminal-environment'],
  },
  {
    name: 'security-dependency-security',
    version: '1.0.0',
    description: 'Audits third-party packages for known CVEs, malicious packages, and supply-chain tampering.',
    category: 'security',
    dir: 'dependency-security',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['shell_execute', 'read_file'],
    optional_tools: [],
    fallbacks: 'Inspect package-lock or pnpm-lock manually for suspicious package versions.',
    title: 'Supply-Chain & Dependency Security Audit',
    purpose: 'Detect vulnerable dependencies and supply-chain risks using pnpm audit or npm audit.',
    when_to_activate: 'Activate when adding new npm/pip packages or running security audits.',
    inputs: 'Lockfile path (pnpm-lock.yaml, package-lock.json).',
    preconditions: 'Project lockfile must exist.',
    procedure: `1. Execute pnpm audit --audit-level=high via shell_execute.
2. Parse audit report for advisory IDs, affected packages, and severity.
3. Identify whether a patch version is available to fix the advisory.
4. Verify package integrity via lockfile checksums.
5. Formulate package upgrade plan if vulnerabilities are detected.`,
    tool_usage: 'Call pnpm audit or npm audit via shell_execute.',
    safety: 'Do not run npm audit fix --force automatically without testing.',
    permissions: 'Safe read-only execution.',
    verification: 'Confirm audit output reports 0 critical or high vulnerabilities.',
    failure_handling: 'If audit reveals unfixable vulnerability, evaluate alternative packages.',
    output_contract: 'DependencyAuditReport with vulnerabilitiesCount, advisories: array.',
    examples: 'Auditing pnpm-lock.yaml for high or critical vulnerabilities.',
    related_skills: ['code-dependency-analysis', 'security-security-audit'],
  },
  {
    name: 'security-permissions',
    version: '1.0.0',
    description: 'Enforces capability-based security boundaries and user confirmation gates on dangerous actions.',
    category: 'security',
    dir: 'permissions',
    risk: 'safe',
    requires_permission: false,
    required_tools: [],
    optional_tools: [],
    fallbacks: 'Default to prompting user for confirmation on all operations.',
    title: 'Capability-Based Permission Enforcement',
    purpose: 'Guarantee that all destructive filesystem, shell, network, and process actions pass through PermissionEngine.',
    when_to_activate: 'Activate before executing any mutating tool operation.',
    inputs: 'Requested tool call, arguments, risk tier, active policy.',
    preconditions: 'PermissionEngine must be initialized.',
    procedure: `1. Inspect tool action and target resources.
2. Evaluate against permission rules (ASK, AUTO, FULL).
3. If tool requires permission and policy is ASK: pause and request user confirmation.
4. If approved: authorize tool execution with bounded capability token.
5. If denied: abort execution immediately with PermissionDeniedError.`,
    tool_usage: 'Enforced via PermissionEngine.',
    safety: 'NEVER allow tools to execute without passing through PermissionEngine.',
    permissions: 'Safe governance mechanism.',
    verification: 'Verify that every tool call has a recorded permission check in telemetry.',
    failure_handling: 'If permission state is ambiguous, reject execution and prompt user.',
    output_contract: 'PermissionEvaluation with isAllowed: boolean, riskTier: string, reason: string.',
    examples: 'Prompting user before executing rm -rf on build directory.',
    related_skills: ['terminal-permissions', 'security-sandboxing'],
  },
  {
    name: 'security-sandboxing',
    version: '1.0.0',
    description: 'Jails filesystem and process execution strictly within authorized workspace boundaries.',
    category: 'security',
    dir: 'sandboxing',
    risk: 'safe',
    requires_permission: false,
    required_tools: [],
    optional_tools: [],
    fallbacks: 'Reject any path containing .. or leading with / outside workspace root.',
    title: 'Workspace Jail & Path Traversal Prevention',
    purpose: 'Confine all file reads, writes, edits, and deletions strictly inside the designated workspace.',
    when_to_activate: 'Activate on every filesystem operation and working directory change.',
    inputs: 'Target path (relative or absolute), workspace root.',
    preconditions: 'Workspace root must be an absolute path.',
    procedure: `1. Resolve target path against workspace root: path.resolve(workspaceRoot, targetPath).
2. Check that resolved path starts with workspaceRoot + path.sep (or equals workspaceRoot).
3. Detect symlink escapes using realpath.
4. If path escapes workspace: throw PathEscapeError and emit path_escape_blocked event.
5. If path is valid: permit operation to proceed.`,
    tool_usage: 'Enforced by ToolOrchestrator and WorkingDirectoryManager.',
    safety: 'STRICT INVARIANT: Never permit tool access to /etc, /var, ~/.ssh, or host root outside workspace.',
    permissions: 'Safe enforcement mechanism.',
    verification: 'Verify tests in tests/security/workspace-jail.test.ts pass with 0 escapes.',
    failure_handling: 'Block operation immediately with security warning event.',
    output_contract: 'SandboxingCheck with isJailed: boolean, resolvedPath: string.',
    examples: 'Blocking an attempted read of ../../../.ssh/id_rsa.',
    related_skills: ['filesystem-read-file', 'security-permissions'],
  },
  {
    name: 'security-threat-modeling',
    version: '1.0.0',
    description: 'Analyzes application attack surfaces, trust boundaries, injection vectors, and auth flows.',
    category: 'security',
    dir: 'threat-modeling',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['search_files'],
    fallbacks: 'Apply STRIDE threat modeling framework manually.',
    title: 'Application Threat Modeling & Attack Surface Analysis',
    purpose: 'Identify trust boundaries, untrusted input ingress points, prompt injection vectors, and data exfiltration risks.',
    when_to_activate: 'Activate when designing new network APIs, auth mechanisms, or web research pipelines.',
    inputs: 'Architecture documentation, API route definitions, input handling code.',
    preconditions: 'System architecture must be understood.',
    procedure: `1. Map data ingress points (user prompts, web search content, HTTP webhooks, files).
2. Identify trust boundaries separating untrusted input from execution runtime.
3. Evaluate prompt injection vectors in tools that consume web content.
4. Assess command injection risks in shell execution helpers.
5. Recommend defensive mitigations (input sanitization, schema validation, sandboxing).`,
    tool_usage: 'Use search_files and read_file to inspect input validation code.',
    safety: 'Read-only analysis.',
    permissions: 'Safe operation.',
    verification: 'Confirm all ingress points have explicit validation or sanitization mechanisms.',
    failure_handling: 'Document unresolved threat vectors in security advisory report.',
    output_contract: 'ThreatModelReport with attackSurfaces: array, threats: array, mitigations: array.',
    examples: 'Threat modeling the web search pipeline to prevent indirect prompt injection.',
    related_skills: ['security-security-audit', 'web-source-verification'],
  },
];
