import { SkillDefinition } from './types.js';

export const terminalSkills: SkillDefinition[] = [
  {
    name: 'terminal-shell',
    version: '1.0.0',
    description: 'Executes non-interactive shell commands with strict timeouts, stream capture, and exit code handling.',
    category: 'terminal',
    dir: 'shell',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['shell_execute'],
    optional_tools: ['process_list'],
    fallbacks: 'Reject execution if shell execution capability is disabled by host policy.',
    title: 'Safe Shell Execution',
    purpose: 'Execute commands in a controlled subshell with working directory tracking and timeout enforcement.',
    when_to_activate: 'Activate when running package managers, compilers, testing tools, or build scripts.',
    inputs: 'Command line string, working directory (optional), timeout_ms (optional).',
    preconditions: 'Command string must be sanitized and classified by risk tier.',
    procedure: `1. Classify command into risk category (SAFE, LOW_RISK, DESTRUCTIVE, PRIVILEGED, NETWORK, IRREVERSIBLE).
2. Check command policy and permission level (ASK, AUTO, FULL).
3. If DESTRUCTIVE or PRIVILEGED, prompt for user confirmation.
4. Execute via shell_execute with timeout (default 30,000ms).
5. Capture stdout, stderr, and exit code.
6. Redact any discovered secrets before returning output.`,
    tool_usage: 'Invoke shell_execute with command, cwd, and timeout_ms.',
    safety: 'Block destructive commands like rm -rf /, fork bombs, or unconfirmed disk formatters.',
    permissions: 'Requires shell permission tier.',
    verification: 'Check exit code is 0 and inspect stdout/stderr.',
    failure_handling: 'If command times out, kill the process group and report duration and partial output.',
    output_contract: 'ShellResult with command, cwd, exit_code, stdout, stderr, duration_ms, timed_out.',
    examples: 'Running pnpm test in repository root.',
    related_skills: ['terminal-command-execution', 'terminal-permissions', 'terminal-diagnostics'],
  },
  {
    name: 'terminal-command-execution',
    version: '1.0.0',
    description: 'Structured command runner tracking execution duration, memory consumption, and standard output buffers.',
    category: 'terminal',
    dir: 'command-execution',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['shell_execute'],
    optional_tools: [],
    fallbacks: 'Degrade to direct single-line shell invocation.',
    title: 'Structured Command Execution & Logging',
    purpose: 'Run and audit CLI commands with structured telemetry and secret detection.',
    when_to_activate: 'Activate when running toolchain utilities (e.g. git, tsc, cargo, python, vitest).',
    inputs: 'Executable binary, argument list, environment variables, working directory.',
    preconditions: 'Target executable must be resolvable in system PATH or workspace.',
    procedure: `1. Construct sanitized argument string without shell injection vectors.
2. Set execution context (working directory, environment variables).
3. Run command via shell_execute.
4. Filter standard output buffers through SecretRedactor.
5. Record execution metrics in telemetry accumulator.`,
    tool_usage: 'Call shell_execute with full command string.',
    safety: 'Escape shell metacharacters unless subshell piping is explicitly required.',
    permissions: 'Requires shell execution permission.',
    verification: 'Verify command completion and status code.',
    failure_handling: 'If exit code is non-zero, capture stderr and classify error in FailureRecovery.',
    output_contract: 'CommandExecutionRecord with exit_code, stdout, stderr, execution_time.',
    examples: 'Running tsc -b ./tsconfig.json to validate type definitions.',
    related_skills: ['terminal-shell', 'core-error-recovery'],
  },
  {
    name: 'terminal-process-management',
    version: '1.0.0',
    description: 'Monitors, inspects, and terminates long-running or background processes.',
    category: 'terminal',
    dir: 'process-management',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['process_list'],
    optional_tools: ['process_kill', 'shell_execute'],
    fallbacks: 'Use ps and kill platform commands via shell_execute if native process tools are absent.',
    title: 'Process Lifecycle & Termination Management',
    purpose: 'Supervise background servers, watchers, test daemons, and terminate rogue processes.',
    when_to_activate: 'Activate when dev servers hang, port conflicts occur, or background tasks complete.',
    inputs: 'Process ID (PID), process name, signal (SIGTERM, SIGKILL).',
    preconditions: 'PID must belong to a spawned child process or user-authorized target.',
    procedure: `1. Call process_list to inspect active inference, dev server, or test processes.
2. Locate target process by PID, name, or listening port.
3. If termination is needed, attempt graceful termination with SIGTERM.
4. Wait for graceful shutdown; if process remains active after 3000ms, send SIGKILL.
5. Verify process is no longer active.`,
    tool_usage: 'Call process_list to enumerate processes; process_kill to terminate by PID.',
    safety: 'NEVER terminate system-critical processes (init, launchd, window manager).',
    permissions: 'Requires process termination capability.',
    verification: 'Confirm process no longer appears in process_list.',
    failure_handling: 'If permission denied when signaling process, alert user that process is owned by another user.',
    output_contract: 'ProcessStatus with pid, status (running/terminated), exit_signal.',
    examples: 'Killing a stale Vite dev server running on port 5173.',
    related_skills: ['terminal-shell', 'terminal-diagnostics'],
  },
  {
    name: 'terminal-environment',
    version: '1.0.0',
    description: 'Inspects and verifies environment variables and platform runtime configurations.',
    category: 'terminal',
    dir: 'environment',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['environment_get'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Execute printenv via shell_execute with secret filtering.',
    title: 'Environment Variable Inspection',
    purpose: 'Check for presence of required environment variables, toolchain versions, and platform flags.',
    when_to_activate: 'Activate during doctor diagnostics, toolchain setup, or missing API key verification.',
    inputs: 'Target variable names or prefix filter.',
    preconditions: 'SecretRedactor must be active to mask sensitive tokens.',
    procedure: `1. Query environment variables using environment_get.
2. Redact sensitive values (API keys, tokens, passwords) showing only mask e.g. [sk-...].
3. Verify presence of required runtime variables (NODE_ENV, PATH, HOME).
4. Return sanitized key-value map.`,
    tool_usage: 'Invoke environment_get with filter keys.',
    safety: 'NEVER expose raw credential values in chat or logs.',
    permissions: 'Safe read-only operation; sensitive values are masked.',
    verification: 'Confirm returned dictionary has all sensitive keys redacted.',
    failure_handling: 'If variable is missing, inform user with instructions on how to set it.',
    output_contract: 'Record<string, string> of sanitized environment variables.',
    examples: 'Checking if OPENROUTER_API_KEY or GROQ_API_KEY is present in environment.',
    related_skills: ['security-secrets', 'terminal-diagnostics'],
  },
  {
    name: 'terminal-permissions',
    version: '1.0.0',
    description: 'Evaluates operation risk tiers and manages interactive user confirmation workflows.',
    category: 'terminal',
    dir: 'permissions',
    risk: 'safe',
    requires_permission: false,
    required_tools: [],
    optional_tools: [],
    fallbacks: 'Default to ASK (prompt for all file mutations and shell executions).',
    title: 'Capability & Permission Policy Evaluation',
    purpose: 'Enforce capability-based security boundaries, risk classification, and confirmation prompts.',
    when_to_activate: 'Activate before executing any mutating filesystem, process, network, or git action.',
    inputs: 'Operation type, target path or command, requested capability level.',
    preconditions: 'PermissionEngine must be initialized with the active workspace policy.',
    procedure: `1. Classify operation risk: SAFE, LOW_RISK, DESTRUCTIVE, PRIVILEGED, NETWORK, IRREVERSIBLE.
2. Check active permission level: ASK, AUTO, or FULL.
3. If AUTO and operation is SAFE/LOW_RISK, authorize immediately.
4. If ASK or operation is DESTRUCTIVE/PRIVILEGED, emit permission_requested event.
5. Await user authorization (approved, denied, session-scoped).
6. Return permission decision to orchestrator.`,
    tool_usage: 'Operates via PermissionEngine in @berkelium/permissions.',
    safety: 'Never bypass permission checks or auto-approve destructive operations in ASK mode.',
    permissions: 'Safe policy evaluator.',
    verification: 'Check that operation is only dispatched if decision is approved.',
    failure_handling: 'If user denies permission, abort operation with PermissionDeniedError.',
    output_contract: 'PermissionResult with action, status (approved/denied), scope, reason.',
    examples: 'Evaluating whether deleting a directory requires user confirmation.',
    related_skills: ['security-permissions', 'terminal-shell'],
  },
  {
    name: 'terminal-diagnostics',
    version: '1.0.0',
    description: 'Runs deep system hardware, OS, memory, storage, and developer environment diagnostics.',
    category: 'terminal',
    dir: 'diagnostics',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['diagnostics_run'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Execute node --version, git --version, and uname -a manually.',
    title: 'System Diagnostics & Health Check',
    purpose: 'Assess platform architecture, chip capabilities, Node version, Git status, and model budget.',
    when_to_activate: 'Activate on bk doctor command or when troubleshooting mysterious build or runtime issues.',
    inputs: 'Diagnostic scope: platform, runtime, providers, tools.',
    preconditions: 'Workspace root must be set.',
    procedure: `1. Call diagnostics_run to gather platform metrics (OS, ARM64, CPU cores, RAM).
2. Check available memory budget for local models.
3. Verify Node.js version >= 20 and Git version.
4. Verify provider credentials and network reachability.
5. Compile comprehensive diagnostic report.`,
    tool_usage: 'Invoke diagnostics_run.',
    safety: 'Read-only diagnostic inspection.',
    permissions: 'Safe operation.',
    verification: 'Verify all diagnostic checks report a status (passed, warning, failed).',
    failure_handling: 'If any sub-check errors, capture error message and mark that check failed.',
    output_contract: 'DiagnosticReport with system info, provider health, tool status, and warnings.',
    examples: 'Running bk doctor to verify Apple Silicon M4 Max memory allocation.',
    related_skills: ['core-agent-runtime', 'project-project-health'],
  },
];
