import { SkillDefinition } from './types.js';

export const testingSkills: SkillDefinition[] = [
  {
    name: 'testing-test-discovery',
    version: '1.0.0',
    description: 'Discovers test runners, frameworks, config files, and test files across the repository.',
    category: 'testing',
    dir: 'test-discovery',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['search_files'],
    optional_tools: ['read_file', 'list_directory'],
    fallbacks: 'Scan tests/ and **/*.test.* directories manually.',
    title: 'Test Suite Discovery & Inventory',
    purpose: 'Identify the project testing framework (Vitest, Jest, Pytest, Cargo test, Go test) and map all test suites.',
    when_to_activate: 'Activate at project onboarding, before running tests, or when planning test coverage.',
    inputs: 'Workspace root path.',
    preconditions: 'Workspace must be accessible.',
    procedure: `1. Inspect package.json or project config for test runner dependencies (vitest, jest, mocha, pytest).
2. Locate test configuration files (vitest.config.ts, jest.config.js, pytest.ini).
3. Search for test files using search_files (**/*.test.ts, **/*_test.go, test_*.py).
4. Categorize tests into unit, integration, security, and golden workflows.
5. Return structured test catalog.`,
    tool_usage: 'Use search_files with test file glob patterns.',
    safety: 'Read-only discovery.',
    permissions: 'Safe operation.',
    verification: 'Confirm test count is non-zero and test framework is detected.',
    failure_handling: 'If no test runner is configured, suggest setting up Vitest or standard runner.',
    output_contract: 'TestDiscoveryCatalog with framework, configPath, totalSuites, testFiles: string[].',
    examples: 'Discovering 50 test files in BerkeliumCodex matching tests/**/*.test.ts.',
    related_skills: ['testing-test-execution', 'project-project-discovery'],
  },
  {
    name: 'testing-test-execution',
    version: '1.0.0',
    description: 'Executes targeted or full test suites, parsing assertions, test counts, and durations.',
    category: 'testing',
    dir: 'test-execution',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['shell_execute'],
    optional_tools: ['read_file'],
    fallbacks: 'Run test command with standard output logging.',
    title: 'Test Execution & Result Parsing',
    purpose: 'Run tests with strict result tracking: DISCOVER -> SELECT -> EXECUTE -> ANALYZE -> FIX -> RE-RUN -> VERIFY.',
    when_to_activate: 'Activate after code editing, during verification loops, and in CI runs.',
    inputs: 'Target test file or filter pattern, timeout, reporter format.',
    preconditions: 'Project dependencies must be installed.',
    procedure: `1. Identify the targeted test command (e.g. pnpm test or vitest run <file>).
2. Execute test command via shell_execute.
3. Parse test output for passed, failed, skipped counts, and duration.
4. If failures occur, extract assertion diffs and failing stack traces.
5. NEVER claim tests passed unless actual test execution returned exit code 0.
6. Return structured test execution summary.`,
    tool_usage: 'Invoke shell_execute with test runner command.',
    safety: 'Do not run test commands that wipe production databases without isolation.',
    permissions: 'Requires shell execution permission.',
    verification: 'Confirm exit code is 0 and passed count > 0.',
    failure_handling: 'If tests fail, feed exact error output into code-debugging.',
    output_contract: 'TestRunSummary with passed: number, failed: number, durationMs: number, exitCode: number.',
    examples: 'Running vitest run tests/unit/chat-schema.test.ts.',
    related_skills: ['testing-test-analysis', 'core-verification', 'code-debugging'],
  },
  {
    name: 'testing-test-generation',
    version: '1.0.0',
    description: 'Authors rigorous unit, integration, and edge-case tests matching existing project conventions.',
    category: 'testing',
    dir: 'test-generation',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['read_file', 'write_file'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Draft test functions and append to existing test suites.',
    title: 'Automated Test Case Authoring',
    purpose: 'Write comprehensive tests covering happy paths, edge cases, error conditions, and invariants.',
    when_to_activate: 'Activate when introducing new features, fixing bugs (regression tests), or improving coverage.',
    inputs: 'Target source file, feature specification, edge cases to cover.',
    preconditions: 'Target implementation and test runner must exist.',
    procedure: `1. Read target implementation and existing tests in the same directory.
2. Identify test idioms (Vitest describe/it/expect, mock patterns).
3. Draft test cases covering: happy path, invalid inputs, boundary conditions, and error states.
4. Save new test suite using write_file in tests/ or adjacent to source.
5. Run the new test suite via testing-test-execution to verify it passes.`,
    tool_usage: 'Use read_file to inspect idioms, write_file to save test file.',
    safety: 'Ensure tests run in isolated environments without side effects on disk or network.',
    permissions: 'Requires filesystem write permission.',
    verification: 'Verify new test suite executes and passes cleanly with 100% assertions green.',
    failure_handling: 'If test fails on first run, verify whether test assumption or source code is flawed.',
    output_contract: 'TestGenerationResult with testFilePath, testCount, coverageEstimate.',
    examples: 'Authoring tests/unit/state-machine-transitions.test.ts for FSM edges.',
    related_skills: ['testing-test-execution', 'code-code-editing'],
  },
  {
    name: 'testing-regression-testing',
    version: '1.0.0',
    description: 'Runs complete test suites to ensure modifications did not break existing behavior.',
    category: 'testing',
    dir: 'regression-testing',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['shell_execute'],
    optional_tools: [],
    fallbacks: 'Run sub-package test suites iteratively.',
    title: 'Full Regression Suite Validation',
    purpose: 'Guard against unintentional regressions across all packages and components.',
    when_to_activate: 'Activate before finalizing tasks, before creating pull requests, or after refactoring.',
    inputs: 'Full test command (e.g. pnpm test).',
    preconditions: 'All modified files must be saved.',
    procedure: `1. Execute full project test command via shell_execute.
2. Monitor all test suite files across all monorepo packages.
3. Verify that all suites pass with zero failures.
4. If any historical test regresses, flag as a regression defect.
5. Prevent task completion until regression is fixed.`,
    tool_usage: 'Call shell_execute with pnpm test.',
    safety: 'Ensure adequate timeout for full regression suites (default 60s).',
    permissions: 'Requires shell execution permission.',
    verification: 'Check that all test suites pass (e.g. 50/50 test files passed).',
    failure_handling: 'If a regression occurs, use git diff to see which edit caused the break.',
    output_contract: 'RegressionTestReport with totalSuites, totalTests, regressions: string[].',
    examples: 'Running pnpm test verifying 262/262 tests pass.',
    related_skills: ['testing-test-execution', 'core-verification'],
  },
  {
    name: 'testing-integration-testing',
    version: '1.0.0',
    description: 'Validates end-to-end interactions between agent runtime, tools, providers, and TUI.',
    category: 'testing',
    dir: 'integration-testing',
    risk: 'medium',
    requires_permission: true,
    required_tools: ['shell_execute'],
    optional_tools: ['read_file'],
    fallbacks: 'Execute component-level unit tests with simulated event buses.',
    title: 'End-to-End & Integration Testing',
    purpose: 'Validate cross-package subsystem integration and end-to-end golden workflows.',
    when_to_activate: 'Activate when validating provider routing, tool execution pipelines, or CLI sessions.',
    inputs: 'Integration test suite path (e.g. tests/integration/agent-loop.test.ts).',
    preconditions: 'All workspace packages must be built or linked.',
    procedure: `1. Verify packages are built via pnpm run build if necessary.
2. Run integration test suite using vitest run tests/integration/...
3. Verify asynchronous event bus event propagation.
4. Verify tool execution and permission checks in realistic scenario.
5. Return integration test report.`,
    tool_usage: 'Call shell_execute with integration test target.',
    safety: 'Mock external network calls to cloud providers in automated integration tests.',
    permissions: 'Requires shell execution permission.',
    verification: 'Confirm all integration steps and event assertions pass.',
    failure_handling: 'If integration times out, inspect event listener unsubscription or unresolved promises.',
    output_contract: 'IntegrationTestResult with scenarioName, eventsObserved, durationMs, status.',
    examples: 'Testing AgentRuntime executing a tool through ToolOrchestrator and PermissionEngine.',
    related_skills: ['testing-test-execution', 'core-agent-runtime'],
  },
  {
    name: 'testing-test-analysis',
    version: '1.0.0',
    description: 'Parses test coverage reports, failure patterns, slow tests, and flakiness metrics.',
    category: 'testing',
    dir: 'test-analysis',
    risk: 'safe',
    requires_permission: false,
    required_tools: ['read_file'],
    optional_tools: ['shell_execute'],
    fallbacks: 'Parse stdout test execution output for timing and failure lines.',
    title: 'Test Coverage & Flakiness Analysis',
    purpose: 'Analyze test coverage metrics, identify untested code branches, and pinpoint flaky tests.',
    when_to_activate: 'Activate when auditing test quality, optimizing test latency, or reviewing PR coverage.',
    inputs: 'Coverage report path (lcov.info, coverage-summary.json) or test runner log.',
    preconditions: 'Test coverage must be generated via pnpm run test:coverage.',
    procedure: `1. Read coverage summary file using read_file.
2. Extract line, function, statement, and branch coverage percentages.
3. Identify files or packages with coverage below project threshold (<80%).
4. Scan test timing logs for slow tests (>500ms).
5. Generate recommendations for missing edge-case tests.`,
    tool_usage: 'Use read_file to inspect coverage JSON or LCOV data.',
    safety: 'Read-only analysis.',
    permissions: 'Safe operation.',
    verification: 'Confirm coverage metrics correspond to actual source files.',
    failure_handling: 'If coverage report is missing, run test runner with --coverage flag.',
    output_contract: 'TestAnalysisReport with overallCoverage, slowTests: string[], uncoveredFiles: string[].',
    examples: 'Analyzing branch coverage on packages/permissions policy evaluator.',
    related_skills: ['testing-test-discovery', 'testing-test-generation'],
  },
];
